### ISSUE TITLE
Verbosity of command line interface

### ISSUE THREAD

**Issue by almereyda** [boringproxy/boringproxy#10]
The current command line interface is very silent about the options that it provides. Taken from https://github.com/boringproxy/boringproxy.io/issues/1 it would be nice to see human readable output for these cases for a start:

- `./boringproxy`  
  A oneliner reminding the user of the available arguments that can be passed to the binary, plus version and licence information in the footer.
- `./boringproxy -h/-help`
  An extended explanation of the arguments that are available.
- `./boringproxy -v/-version`
  Outputs the version of the current build.

**Comment by anderspitman** [comment]
This was basically fixed in #28.
