### ISSUE TITLE
Failed obtaining certificate attempt

### ISSUE THREAD

**Issue by L1so** [boringproxy/boringproxy#100]
Hi, I was about to try this program in order to remote my Raspberry Pi outside my network. But every time I try running `./boringproxy server` it always fail when I type my domain.

`obtaining certificate: [my.domain.xyz] Obtain: [my.domain.xyz] solving challenges: my.domain.xyz: no solvers available for remaining challenges`

I read somewhere else that says this is because port 443 and 80 is closed, I already check with `netstat -tulpen` and https://www.yougetsignal.com/tools/open-ports/ and it turns out to be open. On the same server I also host 3 website which is accessible over http and https, that should eliminate port issue.

**Comment by anderspitman** [comment]
Hi @L1so, if you have other websites already hosted on ports 80/443, how is boringproxy able to bind to those ports?

**Comment by L1so** [comment]
> Hi @L1so, if you have other websites already hosted on ports 80/443, how is boringproxy able to bind to those ports?

So as I understand it, you need port 443 and 80 to be free to be accessible over boringproxy? Am I right?

**Comment by L1so** [comment]
If I need to expose my apache site on my raspberry pi, do I need to install it on Pi ? If so, how would I expose it whereas I don't have static IP on Pi?

**Comment by anderspitman** [comment]
Hi @L1so, sorry for the late response. Did you ever get this working or do you still want to attempt it?

**Comment by L1so** [comment]
> Hi @L1so, sorry for the late response. Did you ever get this working or do you still want to attempt it?

@anderspitman  Well I really want to get this working, but I don't know how, still confused how where to launch the boring proxy service, say if I want to expose my Pi located at my home, with no way of contacting it directly (behind ISP nat, not even ddns service like duckdns able to reach it). How would I do that ?

**Comment by anderspitman** [comment]
You need to run `boringproxy server` on a public server somewhere. Usually this means something like an AWS or DigitalOcean virtual machine.

**Comment by anderspitman** [comment]
Closing for now. @L1so feel free to reopen if necessary.
