### ISSUE TITLE
Email submitting

### ISSUE THREAD

**Issue by mahdi259** [boringproxy/boringproxy#101]
Hi, I entered my email in 'https://boringproxy.io/' and pushed 'submit' but it returned blank page with this notes:

Post "http://localhost:44221/request": EOF

What is the problem?

**Comment by anderspitman** [comment]
Hey @mahdi259, thanks for the report! I started to fix the issue, but when I went to test it out, my browser warned that the demo site has been flagged. This isn't surprising. Any time you set up free tunnels people are going to use it for phishing attacks.

That being the case, I'm going to officially shut down the free demo site. I recommend either hosting boringproxy yourself, or using Cloudflare Tunnel.

Sorry!

**Comment by anderspitman** [comment]
Here are the docs for Cloudflare Tunnel: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps

It's quite easy to use.
