### ISSUE TITLE
Delete Clients

### ISSUE THREAD

**Issue by MANKUD** [boringproxy/boringproxy#102]
Hello, I wanted to know how to delete the unnecessary old clients under the client name menu.

![image](https://user-images.githubusercontent.com/83474708/135024474-230b1254-71cd-4a85-be48-a4f954dee6ad.png)

**Comment by anderspitman** [comment]
Hey @MANKUD, unfortunately this functionality doesn't currently exist. You'll have to modify the `boringproxy_db.json` file and manually delete the clients you don't want. Make sure to back up the file first!

**Comment by MANKUD** [comment]
@anderspitman Oh ok noted and hope for the option to be available in the future release.

**Comment by MANKUD** [comment]
Hello, I tried that but the list does not seem to update after deleting the
entries from the JSON file.

**Comment by MANKUD** [comment]
I restarted the server and seems like it's updated now thanks.
