### ISSUE TITLE
Favicon of web interface missing

### ISSUE THREAD

**Issue by almereyda** [boringproxy/boringproxy#11]
The web interface currently does not serve a favicon. This lets e.g. Firefox display its own icon, which can lead to misunderstandings.

One can produce a simple logo(type) and render it as a favicon, or do it the other way round and let the favicon generator create a logo.

**Comment by almereyda** [comment]
The https://www.faviator.xyz/playground (https://github.com/faviator/faviator) gives me some examples with these settings:

```
{
  "size": 256,
  "text": "bp",
  "dx": 4,
  "dy": 4,
  "fontSize": 91,
  "fontFamily": "PT Sans",
  "fontColor": "#000",
  "backgroundColor": "#eee",
  "borderWidth": 0,
  "borderColor": "#fff",
  "borderRadius": 50
}
```

As PNG this renders into ![favicon](https://user-images.githubusercontent.com/1645308/98114187-2985be00-1ea5-11eb-9ee7-4922c68fc47f.png).

<details>

<summary>A manually edited SVG</summary>

```svg
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 100 100">
  <defs>
    <style type="text/css">
      @import url('https://fonts.googleapis.com/css?family=PT+Sans');
    </style>
  </defs>

<rect x="0"
  y="0"
  rx="50"
  ry="50"
  width="100"
  height="100"
  fill="#eee"></rect>

<text x="50"
  y="78"
  dx="3"
  dy="4"
  fill="#000"
  font-size="92"
  font-family="PT Sans"
  font-weight=""
  text-anchor="middle"
  dominant-baseline="central">bp</text>

<rect x="0"
  y="0"
  rx="50"
  ry="50"
  width="100"
  height="100"
  fill-opacity="0"
  stroke="#fff"
  stroke-width="0"></rect>
</svg>
```
</details>

<details>
<summary>Settings JSON</summary>

```json
{
  "size": 256,
  "text": "bp",
  "dx": 4,
  "dy": 4,
  "fontSize": 91,
  "fontFamily": "PT Sans",
  "fontColor": "#000",
  "backgroundColor": "#eee",
  "borderWidth": 0,
  "borderColor": "#fff",
  "borderRadius": 50
}
```

</details>

**Comment by anderspitman** [comment]
There is actually already a logo, but it wasn't being properly embedded in the executable during the build process. Should be fixed on the demo instance now and will go into the next release.

**Comment by anderspitman** [comment]
Also curious what your thoughts are on the current logo vs this other idea I had: https://github.com/boringproxy/boringproxy/blob/00978992893eb3a4c28ec303b302b8ccac990999/logo_concept.svg

**Comment by anderspitman** [comment]
It may actually make sense to have a different logo for the project and the web UI itself. I'd lean towards keep it simple and leave them the same, but not sure.

**Comment by almereyda** [comment]
That logo is lovely. No need to duplicate efforts here, I think.
