### ISSUE TITLE
Boringproxy-based network workflow as an alternative to the one implemented by socat.

### ISSUE THREAD

**Issue by hongyi-zhao** [boringproxy/boringproxy#110]
I want to implement the following network workflow with `boringproxy` supplied by [`socat`](https://github.com/runsisi/socat):

`$ socat -v -d -d TCP4-LISTEN:9999,fork,reuseaddr socks5:127.0.0.1:10.8.10.220:2021,socks5port=6001`

For details on how the above command works,  I elaborate as follows.

Firstly, `-d` and `-v` used here are debugging/informative options:

```
$ socat -h |egrep -- '^[ ]*-(d|v)'
      -d[ddd]         increase verbosity (use up to 4 times; 2 are recommended)
      -v     verbose data traffic, text
```

About the `fork` and `reuseaddr` options, the following explanations are given by manual page of `socat`:

```
       fork   After establishing a connection, handles its channel in a  child
              process  and keeps the parent process attempting to produce more
              connections, either by listening or by connecting in a loop (ex‐
              ample).
              OPENSSL-CONNECT  and OPENSSL-LISTEN differ in when they actually
              fork off the child: OPENSSL-LISTEN forks before  the  SSL  hand‐
              shake,  while  OPENSSL-CONNECT forks afterwards.  RETRY and FOR‐
              EVER options are not inherited by the child process.
              On some operating systems (e.g. FreeBSD) this  option  does  not
              work for UDP-LISTEN addresses.
              enddit()
      reuseaddr
              Allows  other  sockets to bind to an address even if parts of it
              (e.g. the local port) are already in use by socat (example).
```

Therefore, the above two options are very useful for making `socat` pretend to be a server process that accepts multiple connections and processes.

In this scenario, the localhost `127.0.0.1` and the remote host `10.8.10.220` are located in two separate intranets, which can't directly access the other over the internet. But a bridge/tunnel can be built via the socks5 server running on 127.0.0.1:6001. To be more specifically, the above `socat` command achieves the following aim: 
 
Listening on the localhost 9999 port of TCP4/IPV4 addresses, and build a bidirectional socket/tunnel to the remote HTTP server running on `http://10.8.10.220:2021`, which can be accessed via the locally socks5 server listening on 127.0.0.1:6001.

Finally,  on localhost, when I open `http://127.0.0.1:9999` in a browser, say, Firefox, the actual content displayed is what on `http://10.8.10.220:2021`.

See [here](https://github.com/mholt/caddy-l4/issues/34#issuecomment-967071450) for relevant discussion.

Regards,
HZ

**Comment by anderspitman** [comment]
Hey @hongyi-zhao, I read the thread you linked. Sorry, but I don't really understand what you're trying to accomplish. I'm not familiar with socat or SOCKS at all. Is there something specific you're trying to do with boringproxy?

**Comment by hongyi-zhao** [comment]
> Is there something specific you're trying to do with boringproxy?

Access an intranet website, which can be reached through a socks5 proxy running on the publically VPS.

**Comment by anderspitman** [comment]
I'm familiar with the concepts of SOCKS5, but never used it since it's unencrypted. I feel like it's mostly been replaced with VPNs these days right?

If your SOCKS5 proxy is working for accessing the site, why do you need boringproxy?

**Comment by hongyi-zhao** [comment]
> I'm familiar with the concepts of SOCKS5, but never used it since it's unencrypted.

There are enhancements of socks5, say, [shadowsocks](https://shadowsocks.org/en/index.html), which adds encryption and many other enhancements to the socks5 protocol.

>  I feel like it's mostly been replaced with VPNs these days right?

No, for reasons similar to what I stated above.
 
> If your SOCKS5 proxy is working for accessing the site, why do you need boringproxy?

I just want to know whether there are more flexible tools/workflows which can do the desired job.

**Comment by anderspitman** [comment]
@hongyi-zhao I would say just give it a shot and see if it solves your problem. Have you tried following the instructions on boringproxy.io?

**Comment by hongyi-zhao** [comment]
I have read through the instructions given on https://boringproxy.io/, but I still can’t find where the socks5 proxy I mentioned here can work with `boringproxy`.

OTOH, I want to solve another more complicated scenario: My intranet website needs login authentication, and the initial access port number will change after login. For example, the access address of my internal website is as follows: http://localhost:8080. After logging in, the URL will be changed to http://localhost:8081. How to expose this type of intranet web server to the internet using boringproxy?

**Comment by anderspitman** [comment]
These are all use cases that I'm really not familiar with, so I'm not sure how you would go about it. boringproxy doesn't have any specific SOCKS5 functionality, and that isn't planned. If you try boringproxy for your use case and run into specific problems, feel free to open new issues asking for help, and I'll see what I can do.

**Comment by anderspitman** [comment]
Going to close this for now, since conversation has mostly moved to #113.
