### ISSUE TITLE
Update SSH key algorithm

### ISSUE THREAD

**Issue by anderspitman** [boringproxy/boringproxy#111]
I'm running Arch Linux 5.15.7-arch1-1.

I was seeing the following error when running `boringproxy client`.

```
BoreTunnel error:  Failed to dial: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

Checking the sshd logs, I saw the following:

```
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
```

After a bit of googling, I found this:

https://bbs.archlinux.org/viewtopic.php?pid=1995438#p1995438

Which provides a short-term solution. However, assuming this isn't a bug in Arch I think it would require anyone running a recent OpenSSH server to change this setting. I think a better long-term solution would be to update to a newer key algorithm.

**Comment by anderspitman** [comment]
The OpenSSH 8.8 release notes make it clear that this is intentional, so we need to update (see "Potentially-incompatible changes section"):

https://www.openssh.com/txt/release-8.8

**Comment by almereyda** [comment]
Changing, as in downgrading, security-related system components for a dependent service does not seem helpful. The ed25519 curve is widely supported and systems which don't should effectively not be used anymore.

**Comment by anderspitman** [comment]
I completely agree. Unfortunately I spent half an hour trying to figure out how to generate keys in golang that are compatible with OpenSSH 8.8+ and didn't find an answer. I'm not a crypto expert and I think it would require several hours to figure this out on my own. Would definitely appreciate some help finding a working example.

This seems related:

https://github.com/golang/go/issues/37278

**Comment by ntt4** [comment]
#179 Fixes this issue, however, I did drop support for ssh-rsa in the process. Removing ssh-rsa support does mean that tunnels will have to be re-created so that a new key is generated. This should work with openSSH 6.5 and above.

**Comment by almereyda** [comment]
It appears other people were struggling as well with generating ed25519 keys with Go. Their solutions might provide an implementation path for generating ed25519 keys:

* https://stackoverflow.com/questions/71850135/generate-ed25519-key-pair-compatible-with-openssh
* https://pkg.go.dev/crypto/ed25519#GenerateKey
* https://gist.github.com/rorycl/d300f3ab942fd79e6cc1f37db0c6260f
* https://github.com/charmbracelet/keygen

This does not yet tell us in which way we can programmatically exchange RSA keys with (newly generated) ED25519 keys. Which steps would appear necessary to pass for a successful transition?

**Comment by matbgn** [comment]
Does not completely solve the problem for me (Ubuntu 22.04)...

After creating a first tunnel successfully, the second failed as described here.

**Comment by maietta** [comment]
It's July 2023 and with a fresh install of Ubuntu 22.04 LTS and amd64, I'm now experiencing the same error.

**Comment by anderspitman** [comment]
@maietta it would be fairly surprising to me if your problem had the same root cause. Can you verify that you're getting the same SSHD logs as above, ie something like `userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]`?

Also @matbgn sorry I missed your comment but basically same question for you.

**Comment by maietta** [comment]
Hi @anderspitman, I got it working, but my mistake was an incomplete docker compose setup.

I was trying to bundle this proxy client as part of my service stack using docker compose files, like so:

```
version: '3.7'
services:
  boringproxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boringproxy-server
    restart: always
    command: ["client", "-server", "proxy-domain-endpoint.com", "-token", "toLjOuA8lVTrXLaa01isvEPD6aRZ22PJ"]
    environment:
      - USER=root
```

My Dockerfile looks like:
```
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache wget && \
    wget https://github.com/boringproxy/boringproxy/releases/download/v0.10.0/boringproxy-linux-x86_64 && \
    chmod +x boringproxy-linux-x86_64

EXPOSE 80
EXPOSE 443

# Set the entrypoint command
ENTRYPOINT ["./boringproxy-linux-x86_64"]
```

After switching back to the documented method of direct command line usage, It's working. So it's obviously something missing or wrong with way I am doing this.

I'm using Rootless Docker as well, so that's complicating things a bit. I'll trying to update when I have the correct solution figured out. It'd be nice to deploy this as service via compose files...

UPDATE: I see a modified authorized_hosts. I wasn't immediately aware that this required SSH directly on the host and client. That means what I'm missing is the mapping to my ssh file. Investigating further.

**Comment by anderspitman** [comment]
Yeah, boringproxy integrates tightly with the user's SSH on the server side. Client side it shouldn't modify anything.
