### ISSUE TITLE
"Latest" download link

### ISSUE THREAD

**Issue by chernesk** [boringproxy/boringproxy#122]
In the interest of always having the latest version of this software, it would be great if there was a "latest" link for each of the builds that would always get the newest release. Without that, it's necessary to go to the releases page and parse the latest version number and download what is needed.

For automated updates, especially for security updates, it would be nice to have a link similar to: https://github.com/boringproxy/boringproxy/releases/download/latest/boringproxy-linux-x86_64 where getttng the latest version and updating could be easily scripted.

Thank you!

**Comment by anderspitman** [comment]
I agree. If I'm reading these correctly:

https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

https://github.community/t/why-last-release-is-not-marked-as-latest-release/421

It should be possible to link directly to the latest release, but isn't currently working because I'm creating the tags manually. For the next release (coming very soon), I'll see if I can get this to work properly.

**Comment by chernesk** [comment]
Thank you SO much. Really appreciate all of your work!

**Comment by anderspitman** [comment]
Hey @chernesk, this should be working for the latest release. For example:

https://github.com/boringproxy/boringproxy/releases/latest/download/boringproxy-linux-x86_64

**Comment by chernesk** [comment]
Thank you!

**Comment by anderspitman** [comment]
@chernesk just in case you're still relying on this, as of v0.10.0 we're using goreleaser, which uses different names for the executables by default. So the example above would become:

https://github.com/boringproxy/boringproxy/releases/latest/download/boringproxy_0.10.0_linux_amd64

**Comment by chernesk** [comment]
Thank you!


photograph
*Chris Chernesky
* Owner | Tinderglow Consulting
*p:* (513)486-4569
*e:* ***@***.***
www.tinderglow.com

**Comment by anderspitman** [comment]
Actually I didn't like the new naming scheme, so you can disregard that
comment for now. I'll keep doing it manually until if/when I figure out how
to make goreleaser do the names the way I like.
