### ISSUE TITLE
Is there has anyway to do not use https and assign a port ?

### ISSUE THREAD

**Issue by coder-free** [boringproxy/boringproxy#123]
I want to start boringproxy with out https. Because my server has an nginx running. Nginx used the port 80 and 443. So I want start boringproxy as server that over port may not 80 or 443 (like port 8888).

Then the request path is:

browser -> my vps( nginx -> boringproxy) -> my local server

Is there has anyway to do it.

My vps has some other service running. These service need nginx.

**Comment by anderspitman** [comment]
Hey @coder-free, the next version of boringproxy has some support for HTTP using the `-allow-http` flag, though it might not work in every case. You'll also be able to set `-http-port` and `-https-port`. I'm planning to release in the next few days.

That said, it might be worth considering if you actually need 2 layers of reverse proxies. See the discussion in #105.

**Comment by coder-free** [comment]
@anderspitman Hi, In my case, two-layer of reverse proxies is better. I want boringproxy running after nginx.

I has build boringproxy from source. I run command `./boringproxy server -help`.
It show me:
```
Usage of ./boringproxy:
  -admin-domain string
        Admin Domain
  -allow-http
        Allow unencrypted (HTTP) requests
  -cert-dir string
        TLS cert directory
  -http-port int
        HTTP (insecure) port (default 80)
  -https-port int
        HTTPS (secure) port (default 443)
  -print-login
        Prints admin login information
  -ssh-server-port int
        SSH Server Port (default 22)
```
I run boringproxy with command `./boringproxy server -allow-http -http-port 18888 -https-port 18889 -print-login`. Then I input the domain. Then I input email address. Then I got an error about obtain https certificate.
error is:
```
2022/01/01 15:11:05 demo.example.com: obtaining certificate: [demo.example.com] Obtain: [demo.example.com] solving challenges: demo.example.com: no solvers available for remaining challenges (configured=[http-01 tls-alpn-01] offered=[http-01 dns-01 tls-alpn-01] remaining=[dns-01]) (order=https://acme-v02.api.letsencrypt.org/acme/order/344585610/51763323640) (ca=https://acme-v02.api.letsencrypt.org/directory)
```
I replaced my domian to `demo.example.com` for safety.

Is it possible run only http but have no https?

In fact, my nginx running with https, and the certificate is obtained by myself. I just want to skip obtain certificate. Or use myself certificate? I think if boringproxy running after nginx, the certificate will become useless.

**Comment by anderspitman** [comment]
Ah yeah that makes sense. When I tested this I must have already had the certs locally which is why it didn't fail. I'll need to add a way to completely disable HTTPS.

**Comment by coder-free** [comment]
If this work is completed, please notify me as soon as possible. I can’t wait to try the boringproxy. This software is very useful for me. Thanks very much.

**Comment by anderspitman** [comment]
@coder-free I think I've made the necessary changes. Basically if you change either of the default ports, it displays a warning and should disable automatic certs entirely. Please let me know if this solves your problem.

**Comment by coder-free** [comment]
Hi, I clone the latest code and build it on my vps and local server.
Then run server on vps with:
```
./boringproxy server -allow-http -http-port 18888 -https-port 18889 -admin-domain my.domain.com
```
Run client on local server with:
```
./boringproxy client -server my.domain.com -token mytoken -user admin  -client-name mymac
```
Config a tunnel on manager web site:
![image](https://user-images.githubusercontent.com/2630290/147867066-c1a36b51-f154-49ee-9306-ea014e12229c.png)

I don’t know what "TLS termination" means. Just use the default value 'Client'.

When I request the url `https://mymac.domain.com`. I got an error:
Web site show `Get "http://localhost:34597/": dial tcp [::1]:34597: connect: connection refused`
And my local server (Client) command line show 
`BoreTunnel error:  Failed to dial: %!(EXTRA *errors.errorString=ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)`

VPS (Server) command line has no error. It looks like worked fine.

**Comment by anderspitman** [comment]
So that error specifically has to do with establishing the SSH tunnel. Is your client blocked from outgoing port 22 connections by chance? ie can you SSH from the client to the server VPS normally?

Also, are you using at least OpenSSH server 7.8?

**Comment by coder-free** [comment]
On my local server, I use command `ssh root@my.domain.com`. It connected to my vps success.

On my vps, I use command `ssh -V`. It show me:
```
OpenSSH_7.6p1 Ubuntu-4ubuntu0.5, OpenSSL 1.0.2n  7 Dec 2017
```
So, I need upgrade my OpenSSH version?

**Comment by anderspitman** [comment]
Ahhh yep. Unfortunately it requires a particular SSH feature from 7.8. What version of ubuntu are you on? If the VPS is old definitely be careful about trying to update backported packages.

**Comment by coder-free** [comment]
My ubuntu version is 18.04

**Comment by coder-free** [comment]
My local server ssh version is `OpenSSH_8.6p1, LibreSSL 2.8.3`. Do I need to upgrade it?

**Comment by anderspitman** [comment]
Ok that's not too bad. There should be a way to update to 7.8+. Your local version is fine.

**Comment by coder-free** [comment]
Now openssh version is 8.2, still error:
```
BoreTunnel error:  Failed to dial: %!(EXTRA *errors.errorString=ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)
```

![image](https://user-images.githubusercontent.com/2630290/147875987-a1ed6a3b-8ac4-4d00-96a2-267bcc7d5460.png)

I am not sure the ssh is work. I just download `openssh-8.2p1.tar.gz` and :
```
./configure
make
make install
```
Then I reconnected to my vps and run `ssh -V`, it show me:
```
OpenSSH_8.2p1, OpenSSL 1.1.1  11 Sep 2018
```

**Comment by anderspitman** [comment]
Did you restart sshd?

`sudo systemctl restart sshd`

**Comment by anderspitman** [comment]
Also probably use this to confirm it's running the version you think: https://serverfault.com/questions/545555/how-can-i-find-current-ssh-protocol-version-of-the-current-connection

**Comment by coder-free** [comment]
Yes, I do restart sshd service.

Use ssh -v localhost on my vps. it show me ssh version is 8.2:

![image](https://user-images.githubusercontent.com/2630290/147893491-5edab6aa-018e-44d1-9512-602ac8107bca.png)

**Comment by coder-free** [comment]
I check more log. My vps still running openssh 7.6.

![image](https://user-images.githubusercontent.com/2630290/147893812-a7aa15c2-b994-4637-b47a-186f5855633a.png)

**Comment by anderspitman** [comment]
Yeah it sounds like it didn't install the new version properly. You might have to try some different instructions. Or if it's not too difficult, update to a newer VPS with at least Ubuntu 20.04.

**Comment by coder-free** [comment]
I has upgrade my vps to 20.04.
web site show me :
```
Get "http://localhost:37673/": EOF
```

And client (my local server command line) show me:
```
dial tcp 127.0.0.1:80: connect: connection refused
```

**Comment by coder-free** [comment]
That is my local server stoped. I start it now boringproxy work fine for me.

**Comment by anderspitman** [comment]
So everything is good now?

**Comment by coder-free** [comment]
Yes, thanks very much.

**Comment by anderspitman** [comment]
Awesome, feel free to reach out if you run into more problems. Also just so you know, I'm going to be moving general support over to the [IndieBits forums](https://forum.indiebits.io/c/boringproxy-support/9), so unless you think you've found a bug, that would be the best place to post in the future. You can log in with your GitHub account.
