### ISSUE TITLE
32bit support, please

### ISSUE THREAD

**Issue by voarsh2** [boringproxy/boringproxy#14]
I ran it on 64bit for testing, but my main setup is 32bit.

Can you build 32bit support please?

Otherwise, I will have to upgrade my motherboard and CPU... which ain't happening soon.

**Comment by anderspitman** [comment]
Shouldn't be too hard to add :+1:

**Comment by voarsh2** [comment]
> Shouldn't be too hard to add 👍

Great! 🎆 
I'm on Ubuntu 18, i686, FYI.
Thanks.

**Comment by anderspitman** [comment]
Hey @voarsh2, I've released version v0.2.0 which includes 32 bit builds for Linux and Windows. Let me know if this covers your needs.

**Comment by anderspitman** [comment]
https://github.com/boringproxy/boringproxy/releases/tag/v0.2.0

**Comment by voarsh2** [comment]
Thanks!
I'll give it a test and report back.

**Comment by voarsh2** [comment]
I gave it a twurl and I got:
Failed to PUT client on my 32bit client.
In the past I followed instructions exactly on 64bit and it worked.
