### ISSUE TITLE
Change user used for SSH tunnel

### ISSUE THREAD

**Issue by alexsanderp** [boringproxy/boringproxy#142]
Hi, @anderspitman

I noticed that the keys are generated and added in the /root/.ssh/authorized_keys file with flags allowing only tunnels.

However, if we have a security breach in the SSH protocol, it would be possible for the user to access root.

My suggestion would be to give the option to choose which system user will be used in the tunnel, so we can use a user with less privileges.

**Comment by anderspitman** [comment]
Whatever user runs the boringproxy server is what will be used for all SSH operations (see [here](https://github.com/boringproxy/boringproxy/blob/23f7a06358aad0e667d741927cdf82fbccc418c6/tunnel_manager.go#L31). I'd definitely recommend using a non-admin boringproxy user. If you're using systemd to run a service, you can set `User` in the unit file.

**Comment by anderspitman** [comment]
Going to go ahead and close this. Feel free to reopen if your issue hasn't been resolved.
