### ISSUE TITLE
sshuttle support

### ISSUE THREAD

**Issue by Yorizuka** [boringproxy/boringproxy#173]
First im going to say that I love boringproxy, this project made it finally possible for me to easily self host from home. Out of all the solutions iv tried this was the nicest to use, thank you for freeing me from my ISP's CGNAT & lack of ipv6.

### The problem
But lately iv rant into a big problem and its slowly turning into a show stopper, about a month ago I decided to self host a matrix home server, for the first few hours it worked fine, but as I joined rooms and traffic increased to it. The connections started to get bad, it got bad fast. Some requests take minutes to complete.

My understanding is that this is due to all my traffic for this matrix server being pushed through a single ssh tunnel, and that this is called the "TCP over TCP" problem. I know its not simple to solve, but I have some recommendations on how this issue could be helped.

### How to solve this
The first solution I have thought of is to integrate another project into this one, there is a tool called sshuttle, and it helps solve the TCP over TCP problem. I believe adding support for it will not require a lot of changes to boringproxy and it will solve this large issue.

Another solution I will purpose that I dont think is as good, but I will still mention, is dynamically creating more then one ssh connection for busy domains and load balancing between them.

**Comment by anderspitman** [comment]
Hi @Yorizuka, glad boringproxy is working for you.

This is a good discussion to have. I'm trying to move away from GitHub as much as possible. Would you mind copying your post over to [forum.indiebits.io](https://forum.indiebits.io/c/boringproxy/9)? If it's too much trouble that's ok but would prefer that.

Thanks!

**Comment by Yorizuka** [comment]
Done, https://forum.indiebits.io/t/solving-tcp-over-tcp-slowdown-adding-sshuttle-support/82
