### ISSUE TITLE
Can not connect from client

### ISSUE THREAD

**Issue by ramon1604** [boringproxy/boringproxy#175]
After starting server using Digital Ocean with droplet and ubuntu 20.04, running comand:
./boringproxy-linux-x86_64 server -admin-domain tunnel.ptzcamcenter.com

the clients is a raspberry pi 3b+ and running command:
./boringproxy-linux-arm client -server tunnel.ptzcamcenter.com -user admin -token <token here> -client-name rpi_001

always get:
Failed to create client. Are the user ('admin') and token correct? HTTP Status code: 404. Message: 404 page not found

note: <token here> used instead of real token for security.

**Comment by ramon1604** [comment]
the token is prperly placed. we did not include it for security reasons:
-token tokenhere

**Comment by almereyda** [comment]
Did you try with using specific client tokens? There have been recent changes in using authentication tokens. My PR for updating the documentation is currently hanging a bit, but soon ready.

Try creating a dedicated user and a dedicated token for the desired client. Then you would ideally be able to run the client with something close to:

    boringproxy client -server tunnel.ptzcamcenter.com -token tokenhere

Is this the case?

**Comment by ramon1604** [comment]
we will try and let you know. thanks for the help.

**Comment by almereyda** [comment]
I have updated my comment to be more specific.

**Comment by ramon1604** [comment]
created user in GUI: rpi001 and token: MKlUiRrWFLrEuQL0uxkE5lAxFZf01Bhz
comand is: ./boringproxy-linux-arm client -server tunnel.ptzcamcenter.com -token MKlUiRrWFLrEuQL0uxkE5lAxFZf01Bhz -user rp001 -client-name rp001

error is: Failed to create client. Are the user ('rp001') and token correct? HTTP Status code: 404. Message: 404 page not found

**Comment by ramon1604** [comment]
can you send me a step by step instructions for server and client as of now. It seems a lot has changed since video in boringproxy.io

**Comment by ramon1604** [comment]
it is working with version 0.8.2 not with 0.9.0

**Comment by anderspitman** [comment]
Hey @ramon1604, glad it's working, but it would be ideal to get this working on the latest release, as the old way of doing things is less secure. If someone gets ahold of your client token they can completely take over the boringproxy account on the server.

If you're willing to try again with the new version, first thing to do is drop the `-user` and `-client-name` from the command line. They're no longer necessary if you're using a client token (choose client when creating the token). So it would look like this:

` ./boringproxy-linux-arm client -server tunnel.ptzcamcenter.com -token MKlUiRrWFLrEuQL0uxkE5lAxFZf01Bhz`

**Comment by anderspitman** [comment]
Sorry about the video being out of date. There have definitely been a lot of changes. It's probably time to make a new video. I'm working on some important features right now. Once those are done I'll consider how to get a new video made soon. It may actually be about time for a 1.0 release.

**Comment by ramon1604** [comment]
thanks, everything is working fine. using version 0.8.1

Regards
________________________________

**Comment by anderspitman** [comment]
Fair enough. Feel free to open a new issue if/when you need to upgrade.
