### ISSUE TITLE
Buffering

### ISSUE THREAD

**Issue by sharkshead** [boringproxy/boringproxy#177]
I seem to be having a buffering problem with Boring Proxy. The web sites I'm proxy'ing with BP use a HTML5 EventSource to send a real-time data stream back to the browser. It is not a constant stream of data, just new sensor values that have changed. This might be every 1/2 second for a noisy sensor, or every 30 seconds if the sensor's world is quiet. And multiple sensors send new values over the same EventSource.

This works great when connected directly to the web server, whether that's in my lab or over the internet, but it's not so good when connecting though BP. It seems to me that somewhere along the path there is a 4K buffer, and the real-time stream going through the EventSource connection is buffered until this 4K is full, and then the entire 4K is sent in one big lump. This negates the whole idea of a real-time stream, unfortunately.

Is this a known issue, or perhaps a design feature, or maybe I'm completely wrong. If it is a feature, is it possible to include a flag to turn the buffer off?

To add some detail, the BP server is running Ubuntu on Intel, the clients are Raspberry Pi Zero W's running Raspios, and the web browsers are Safari, Firefox and Chrome running on a couple of iMac's and Mini's. The web server running on the PI Z W's is apache2, and the target of the EventSource is C++ code written by me, as a cgi-bin under apache2, and it flushes it's buffers after writing each new data line to the output stream.

Comments and help greatly appreciated.

**Comment by anderspitman** [comment]
Hey @sharkshead, thanks for the report. This is an important use case and needs to work. Would it be too much trouble to copy this report over to a new thread on https://forum.indiebits.io/c/boringproxy/9?

I'm trying to move away from GitHub for boringproxy support. You can use your GitHub account to login there.
