### ISSUE TITLE
Is it possible to access proxy on another local computer

### ISSUE THREAD

**Issue by goldalworming** [boringproxy/boringproxy#195]
Hi, is it possible to connect proxy from tunneling

proxy usually use server 
pc1 --> proxy[server] --> domain

I need to put proxy behind tunneling

pc1 --> tunneling[server] --> proxy[pc2] --> domain

proxy used as middleman to mimick all connection so I can change myip dynamically to private ip

**Comment by anderspitman** [comment]
Hi @goldalworming, support is now provided at https://forum.indiebits.io/. You can log in there with your GitHub account.

Thanks,
//anders
