### ISSUE TITLE
ssh error.

### ISSUE THREAD

**Issue by TebbaaX** [boringproxy/boringproxy#196]
Getting the same Error Running the Client on Ubuntu (WSL) 
- Running OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
- Running on the server on Digital Ocean VPS / Namecheap (Works well.)

is there something i'm missing? (Same error when running the Windows version)
![error](https://user-images.githubusercontent.com/58398485/197419703-46440ae3-8e44-4113-a98f-b1a4e0b2e980.PNG)

_Originally posted by @TebbaaX in https://github.com/boringproxy/boringproxy/issues/120#issuecomment-1288208044_

**Comment by anderspitman** [comment]
Hey @TebbaaX, support is now handled at https://forum.indiebits.io/. You can log in there with your GitHub account.

Thanks,
//anders
