### ISSUE TITLE
uuhh.... this looks great

### ISSUE THREAD

**Issue by palitu** [boringproxy/boringproxy#2]
awesome!  i just did a quick run through and this is going to make my life a bore!

I can see a bunch of hits on my boring server from outside players, so happy that digital ocean takes the brunt of that, and not my servers :)

Thanks!  this looks like it could be a game changer for me :)

**Comment by anderspitman** [comment]
Hey @palitu, thanks! Hope you find it useful. Definitely let me know if you run into any issues.
