### ISSUE TITLE
Remote file name has no length! Failed writing recieved data to disk/application

### ISSUE THREAD

**Issue by msdosfx** [boringproxy/boringproxy#202]
I am running an Ubuntu VPS on Hetzner from a user with sudo priveleges. I am using the web console on Hetzner website. I am trying to run the curl command for linux x86. It results in: curl: Remote file name has no length!
curl: (23) Failed writing recieved data to disk/application
-bash: //github.com/boringproxy.com/boringproxy/boringproxy/releases/latest/download/boringproxy-linux-x86-64: No such file or directory

Sorry if this is obvious or I am doing something wrong; I am not experienced.

**Comment by anderspitman** [comment]
Hi @msdosfx. Please use the forums for future support requests:

https://forum.indiebits.io/c/boringproxy/9

Fortunately your problem is pretty easy to solve. Your URL is incorrect. Try this:

https://github.com/boringproxy/boringproxy/releases/latest/download/boringproxy-linux-x86_64
