### ISSUE TITLE
getting error when creating tunnel

### ISSUE THREAD

**Issue by raihangit000** [boringproxy/boringproxy#203]
whenever  i tried  to creat tunnel i got error

"open /root/.ssh/authorized_keys: no such file or directory"

what i need to do?

<a href="https://ibb.co/hKtywtG"><img src="https://i.ibb.co/CnTzDTj/2023-01-31-31115312-AM-ece-U4-TF7-IO.png" alt="2023-01-31-31115312-AM-ece-U4-TF7-IO" border="0"></a>

**Comment by anderspitman** [comment]
Hi @raihangit000, support is offered over on the forums. You can log in with your GitHub account. Thanks!

https://forum.indiebits.io/c/boringproxy/9
