### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by Stunt0265** [boringproxy/boringproxy#206]
How does the performance of boringproxy compare to Cloudflare tunnels?  Or Wireguard?

**Comment by anderspitman** [comment]
boringproxy is built on SSH, which uses a single TCP connection to multiplex channels. Generally speaking I would expect it to have slower performance than WireGuard, and probably Cloudflare Tunnels as well (at least using QUIC or similar). The main problem is head-of-line blocking.

**Comment by anderspitman** [comment]
Closing. Feel free to ask any additional questions.
