### ISSUE TITLE
[Feature Request] Replace client app with ssh

### ISSUE THREAD

**Issue by finzzz** [boringproxy/boringproxy#22]
Can you do something like serveo.net where I don't need to download any app and just use SSH?

**Comment by anderspitman** [comment]
It actually already works that way! But you need to download the private key for the tunnel. See the script here which shows the steps:

https://github.com/boringproxy/boringproxy/blob/6b36c256c32746e293a1bf7ce6ed3d45862501b7/scripts/tunnel.sh

It might be a bit out of the date, but shows the basic idea.

Note: I don't intend for boringproxy to become an alternative to free services like serveo.net. Those typically get overrun with spammers and phishers. The boringproxy demo site is for people to try it out without having to download themselves. If it becomes a problem I'll just shut it down. I might start a paid service at some point in the future though.

**Comment by voarsh2** [comment]
> Note: I don't intend for boringproxy to become an alternative to free services like serveo.net. Those typically get overrun with spammers and phishers. The boringproxy demo site is for people to try it out without having to download themselves. If it becomes a problem I'll just shut it down. I might start a paid service at some point in the future though.

This is troubling. When can I expect this project to collect dust? 
There's already ngrok.io, lynk.sh and more....

**Comment by anderspitman** [comment]
I don't intend for the project to collect dust any time soon, seeing as I use it every day for hosting my own things. I was specifically talking about the demo site. It's not intended for people to use for hosting. It's just to demo how the software works. If people abuse it I'll just turn it off rather than trying to moderate.

**Comment by finzzz** [comment]
> I don't intend for boringproxy to become an alternative to free services like serveo.net. Those typically get overrun with spammers and phishers.

I know, I just want to selfhost my own tunnel and connect it similar to serveo but with password. I'll check it out if it works

**Comment by anderspitman** [comment]
Gotcha. Since you prefer using your own SSH client, [SirTunnel](https://github.com/anderspitman/SirTunnel) might be a better fit for you. It's very minimal/easy. It lets you control tunnels from the SSH client rather than a web UI on the server.

**Comment by finzzz** [comment]
But can it forward tcp connection? Or is it http only?

**Comment by anderspitman** [comment]
It's just a normal SSH tunnel, so it can do everything an SSH tunnel can. To forward TCP you'll need to have `GatewayPorts=yes` or `GatewayPorts=clientspecified` in your `sshd_config`. Make sure you understand the implications of setting that before doing it.

**Comment by finzzz** [comment]
Alright thanks

**Comment by anderspitman** [comment]
Going to go ahead and close this. Feel free to reach out if you have any more questions or issues.
