### ISSUE TITLE
Static binary for release

### ISSUE THREAD

**Issue by tomberek** [boringproxy/boringproxy#24]
Release with CGO_ENABLED=0 for a static build. Seems to work.

**Comment by anderspitman** [comment]
Hey @tomberek, not sure I'm understanding correctly. The current release (v0.4.0) is static binaries build with CGO_ENABLED=0, as per the build scripts here:

https://github.com/boringproxy/boringproxy/blob/7034cb8671390537449adffe4a4be69b60b7f387/scripts/build_arch.sh

It's possible I messed up the built process though. What are you seeing?

**Comment by tomberek** [comment]
okay, i was just doing `go get`/`go install`
