### ISSUE TITLE
HTTPS tunneling ipv6

### ISSUE THREAD

**Issue by mcsurfi** [boringproxy/boringproxy#26]
Hi

I have a vps with a public ipv4 and ipv6 address. If i use this vps as server for https tunneling it does not work. Are boringproxy ipv6 ready? Here the error message:

Get "http://localhost:36561/": dial tcp [::1]:36561: connect: connection refused

::1 ist the ipv6 localhost address.  

netstat -atn:
tcp        0      0 127.0.0.1:36561         0.0.0.0:*               LISTEN

The tunnel are created but listening only on the ipv4 (127.0.0.1) localhost ip address. Boringproxy tried to connect at the ipv6 (::1) localhost address.

If i disable ipv6 on the vps completly it works...

Florian

**Comment by anderspitman** [comment]
Unfortunately it only supports ipv4 currently. ipv6 should be possible, but I'm not sure when I'll be able to get to it since it's not something I need myself. Part of the reason tools like boringproxy are useful is because ipv4 addresses are scarce. This is less of a problem with ipv6.

**Comment by anderspitman** [comment]
If you're using boringproxy and this is a blocker for you, I can try to get it done sooner than later.

**Comment by mcsurfi** [comment]
Hi

at the moment it's not important for me but in the feature it will b nice if boringproxy will work with ipv6.

Florian

**Comment by anderspitman** [comment]
IPv6 should be working as of v0.9.0+
