### ISSUE TITLE
Debian amd64 (cannot put client)

### ISSUE THREAD

**Issue by voarsh2** [boringproxy/boringproxy#31]
When running on ubuntu amd64 I can start the client just fine.

But when I try on debian I always get:
```
Failed to PUT client
```

**Comment by anderspitman** [comment]
That's interesting. If there was a problem between distros I would expect it to be a dynamic linking issue and just fail to launch. What we really need here is a better error message to know more what's going on. I will add that soon and ping you when it's ready to test. Due for a new release anyway.

**Comment by anderspitman** [comment]
Alright @voarsh2, can you give v0.5.0 a shot when you get a chance?

https://github.com/boringproxy/boringproxy/releases/tag/v0.5.0

**Comment by voarsh2** [comment]
Thanks!
Fixed.
