### ISSUE TITLE
Jellyfin cannot set https - SycPlay doesn't work

### ISSUE THREAD

**Issue by voarsh2** [boringproxy/boringproxy#35]
![image](https://user-images.githubusercontent.com/60437695/104131884-59ec4b80-5371-11eb-9180-e18da92d2372.png)

It expects me to give the location of the certificate.
Obviously with boringproxy, the server version has it, not the client.

Things like SycPlay doesn't work via boringproxy.

**Comment by anderspitman** [comment]
Actually, boringproxy lets you choose whether the client or the server controls the certs. That's what the "TLS Termination" setting is. The default is server, which means the server will contact Let's Encrypt for a cert automatically. If you set it to "Client", then the client will do that instead and the server will simply pass traffic to the client. If you set it to "Passthrough", then both the server and client won't do any TLS and it will be up to the application (or you) to get a certificate.

What you might try in your situation is set it to "Client", start up a tunnel. That will get you a cert on the client. Then delete the tunnel and recreate it as "Passthrough", and use SyncPlay to select the cert previously created by the client (check the [certmagic docs](https://github.com/caddyserver/certmagic#storage) for where the certs are stored by default, or you can pass the `-cert-dir` option to boringproxy client to tell it where to store them.

**Comment by anderspitman** [comment]
Going to close for now. Let me know if you have more details or questions.
