### ISSUE TITLE
TCP port forwarding on boringproxy

### ISSUE THREAD

**Issue by 39p** [boringproxy/boringproxy#36]
Hey, I was wondering if TCP forwarding is possible and if not, a suggestion I would recommend. Boringproxy works fantastic for HTTP and I have been using it on my domain, however something I would want like other service like ngrok is TCP forwarding.

I was just wondering if this is possible because I can't get it working, when I have a tcp service on port 10058 and setup boringproxy for it, I can't access it and if I try to click the URL
`Get "http://localhost:42297/": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "Exception:"`

So I'm assuming TCP doesn't work, and this is something I would recommend, `Allow External TCP` doesn't work either on or off

**Comment by anderspitman** [comment]
Hi @39p, have you set GatewayPorts=clientspecified in your sshd_config? This still needs to be added to the docs. See #25.

**Comment by 39p** [comment]
Yep, that's the reason. I just did that on my vps, rebooted, now it's works prefectly with TCP. thanks!

**Comment by anderspitman** [comment]
Excellent, let me know if you have any other issues. I'll bump the priority for #25.
