### ISSUE TITLE
Add support for HTTP

### ISSUE THREAD

**Issue by anderspitman** [boringproxy/boringproxy#42]
Advantages:

* Easier to run behind other reverse proxies (see #38)
* Can enable ACME HTTP challenge while we're at it
* HTTP is insecure but it has its place. If the choice is between someone putting their site on the web as HTTP vs not because they couldn't figure out TLS, I'll take the HTTP.

**Comment by almereyda** [comment]
This will be useful for a setup that I am currently planning to setup with `boringproxy`, not knowing this was currently not yet possible.

```
+-----------+         +-----------+                              
| OpenWRT   |         | Nextcloud |                              
| hostnames |         | http      |                              
+-----|-----+         +------|----+                              
      |                      |                                   
      |                      |                                   
      |                      |                                   
+-----|-----+        +-------|------+                            
| LAN User  ---------- Caddy        |                            
+-----------+        | http + https |                            
                     +-------|--|---+                            
                             |  |                                
                             |  |                                
                             |  |                                
                            +|--|----------+                     
                            ||Boringproxy  |       +-----------+ 
                            ||http + https --------- WAN User  | 
                            +|--|----------+       +-----|-----+ 
                             |  |                        |       
                             |  |                        |       
                             |  |                        |       
                     +-------|--|---+             +------|------+
                     | ACME Server  |             | PowerDNS    |
                     +--------------+             | authorative |
                                                  +-------------+
```

In this setup the authorative name server and the recursive LAN resolver will serve different IP addresses for the desired host, but both Caddy and Boringproxy are expected to generate and serve valid TLS certificates through an ACME server.

This has the effect that the Nextcloud can be accessed locally at full LAN speed, while being available securely on the public internet, both with the same address and scheme.

**Comment by anderspitman** [comment]
@almereyda what's your timeline for this? I'm pretty strapped at the moment. It would be ideal if you can wait a couple-three weeks.

**Comment by almereyda** [comment]
Actually an alternative path has been laid out by you in https://github.com/boringproxy/boringproxy/issues/35#issuecomment-758091437

I'm not pressed in any way, this is an experiment for aesthetical tryouts extending from the experiences in #8 and #38.

**Comment by anderspitman** [comment]
Sounds good. Let me know if anything changes and I may be able to bump the priority.

**Comment by anderspitman** [comment]
This should be working in the latest release, using `-http-port`, `-https-port`, and `-allow-http`.
