### ISSUE TITLE
Not routing as expected!

### ISSUE THREAD

**Issue by arnabdafadar** [boringproxy/boringproxy#43]
I have setup the Boringproxy server on a Google Cloud instance with HTTP and HTTPS traffic open.
I am trying to connect to a raspberrypi running nextcloud on 192.168.29.144:8080.
The login page of the server creates the subdomain pointing to the raspberrypi. However,  on clicking the created subdomain, the request is not successfully routed to the raspberrypi. 
Followed the tutorial line by line still no luck. 
Not sure if it is a bug or a error in the setup.
Looking for some help.

**Comment by anderspitman** [comment]
Hi @arnabdafadar. I can try to help but I can't devote a lot of time to it. I'll need more details if you can tell me anything about the behavior you're seeing or specific errors.

Can you also take a look at this comment (the rest of the thread may be useful as well):

https://github.com/boringproxy/boringproxy/issues/8#issuecomment-722528521

**Comment by arnabdafadar** [comment]
Hey @anderspitman Thanks for the quick reply. I did some digging around the previous issue and changed the Gateway ports to "clientspecified". Still I am getting a bad redirect whenever I am trying to open the tunnel links from the boringproxy server. I parked the NextCloud as of now and I am simply tunnelling my PiHole setup (non docker install) in the raspberry pi. **(Tunnel looks like: pp.brainybytes.fun:34263 -> raspi -> 127.0.0.1:90)**. I have the pihole interface setup on port 90.
The only thing that is working as of now is the login page of the OpenMediaVault **( oo.brainybytes.fun:34365 -> raspi -> 127.0.0.1:89
 )** in my raspberrypi (I have my openmediavault login page on port 89).
I am attaching some screenshots which might help you in debugging the issue.

![works_fine](https://user-images.githubusercontent.com/64244912/106705719-7a2bc500-6614-11eb-9879-d057cdc5d2bf.jpg)
![gcp](https://user-images.githubusercontent.com/64244912/106705588-42bd1880-6614-11eb-8ff3-d6e43c70f9b6.jpg)
![raspberrypi](https://user-images.githubusercontent.com/64244912/106705599-481a6300-6614-11eb-8956-077bf1817586.jpg)
![redirect_error](https://user-images.githubusercontent.com/64244912/106705600-48b2f980-6614-11eb-8900-59506355bedc.jpg)
![server](https://user-images.githubusercontent.com/64244912/106705601-494b9000-6614-11eb-8e55-6ad0cec2038d.jpg)

**Comment by arnabdafadar** [comment]
@anderspitman A super quick update.
I issue seems to be with proper redirection. e.g....
My nextcloud locally runs on the URL (192.168.29.144:8080/login)
The boringproxy server sets up the tunnel like cc.branybites.fun --> 192.168.29.144:8080 (without the /login part)
If I manually write the URL like cc.branybites.fun/login...voila! The nextcloud login page opens.
Then when I try to login with the credentials, the page does not automatically redirect to the nextcloud dashboard, instead freezes on the login screen.
If I manually write the URL like https://cc.branybites.fun/apps/files/, then the dashboard of the nextcloud opens.
Somehow it is not redirecting properly. I am not sure if this piece of information is of any importance to you, but I thought of letting you know in case if there is something that can be fixed. :)

**Comment by anderspitman** [comment]
Thanks for the screenshots. A couple things:

I'm pretty sure you're right about the redirects being the problem. That comment I linked on issue #8 explains what I had to do to get nextcloud to work. Unfortunately there isn't much boringproxy can do in these situations. Each individual server software has to be configured to run behind a reverse proxy. It might be easier to first get your setup working with Caddy or nginx, then try boringproxy, because it's far less likely that those programs have bugs.

Also, it looks like you're using an older version. I recommend using the latest release. I don't think this will fix your current problem, but it's recommended anyway.

**Comment by arnabdafadar** [comment]
Hey @anderspitman . Thanks for your quick reply and for taking out time to read the issue. The nextcloud issue got fixed by specifying the environment variables on the docker image, as suggested by you. I am deploying some more self-hosted applications on my server and will test the accessibility of those using boring-proxy. I Will do some digging around and let you know if the other applications require any special parameters for the boring-proxy to work. 

Also, one thing I noticed while creating the server on a cloud instance (AWS/Google/Oracle/Azure), one needs to have a password-less authentication setup (Private-Public key pair) to ssh into the cloud, otherwise creating tunnels from the server throws an error like "/home/<user>/. ssh/id_rsa not found". If this is the expected behavior, then it would be worth mentioning this point on the Setup Instruction Document.

Anyways, thanks for making this simple and awesome tool. It will be a boon for the home-server guys sitting behind a CGNAT from their ISP. :)

**Comment by arnabdafadar** [comment]
BoringProxy is working as intended! Thanks for the awesome tool! :)

**Comment by anderspitman** [comment]
Glad you got it working :+1:

Your ssh key experience seems a bit off to me. For individual tunnels, a separate key is generated on the server, and transferred over HTTPS to the client, so `/home/(user)/.ssh/id_rsa` should never be used on the client side. Where are you seeing that error, and the client, server, in the browser when you try to load the tunnel?

**Comment by arnabdafadar** [comment]
I am seeing the error on the browser whenever I am trying to create a tunnel (only if i do not have the public-private key pair setup).

**Comment by anderspitman** [comment]
Hm is it popping up in the middle of the screen after you click the Add Tunnel "Submit" button?

**Comment by arnabdafadar** [comment]
@anderspitman Yup, you got it right. That is exactly what is happening.
