### ISSUE TITLE
Switch executable naming from amd64 to x64 or x86_64

### ISSUE THREAD

**Issue by anderspitman** [boringproxy/boringproxy#45]
Multiple users have downloaded the wrong file because the name is so similar to arm64

**Comment by Zygodon** [comment]
Thanks, @anderspitman. That solved it for me. Maybe the problem is that the file mentioned in the curl request in your installation instructions has no suffix indicating the compiler version. Maybe just a note there drawing attention to the issue?

**Comment by anderspitman** [comment]
Ah yes I didn't realize the instructions were pointing to such an old version. I'll update that, thanks!
