### ISSUE TITLE
Unable to obtain SSL certificte

### ISSUE THREAD

**Issue by Zygodon** [boringproxy/boringproxy#46]
Hi @anderspitman, I'm hitting a snag, boringproxy terminates without issuing URL:

pi@raspberrypi:~ $ ./boringproxy_arm server
2021/02/04 16:12:26 Starting up
2021/02/04 16:12:26 Enter Admin Domain: 
stwhh.website
2021/02/04 16:12:52 stwhh.website: obtaining certificate: [stwhh.website] Obtain: [stwhh.website] solving challenges: stwhh.website: no solvers available for remaining challenges (configured=[tls-alpn-01] offered=[http-01 dns-01 tls-alpn-01] remaining=[http-01 dns-01]) (order=https://acme-v02.api.letsencrypt.org/acme/order/111677726/7711144395) (ca=https://acme-v02.api.letsencrypt.org/directory)
pi@raspberrypi:~ $ 

The first time I ran boringproxy, I was asked for an email address, as descibed in boringproxy.io. I got exactly the same response, though, and no URL. It's a Namecheap domain name with an A@ record and an A* record (what they seem to call a URL redirect record).
It's a domain name I have used for other purposes previously (WordPress), and was reachable with https.
I'm sure this is my problem not yours, but I would be grateful for any pointers.
Thanks - and thanks too for your quick response to my difficulty with _arm (sic; my RPi is running 32 bit) vs _amd64

**Comment by anderspitman** [comment]
Are you sure there's nothing between boringproxy and the public internet? No firewalls or other reverse proxies like nginx, Caddy, Apache, etc?

**Comment by arnabdafadar** [comment]
Hi, @Zygodon Did you check whether port 80 and 443 is accessible? The error might be because the inbound traffic on 80 / 443 port is being blocked by your router or firewall.
I host my server on an Oracle Cloud Instance and I used to get the exact same error. Upon checking, I realized that the inbound traffic on 80/443 port wasn't open on the oracle cloud instance and hence the issue.
I opened up the ports and the issue got resolved. As @anderspitman suggested, check your firewall or your router once.

**Comment by Zygodon** [comment]
Thank you @anderspitman and @arnabdafadar . You are both right: nginx was running on my server; also although I had remembered to forward port 80, I had forgotten about 443. And then, thirdly, the A certificates on my domain name were not quite correct. So this issue is resolved now and I can access the web interface.
I want to say, thank you to @anderspitman for making this amazing software available.

**Comment by anderspitman** [comment]
Excellent, glad you got it working. Thanks for the assist @arnabdafadar.

**Comment by arnabdafadar** [comment]
> Excellent, glad you got it working. Thanks for the assist @arnabdafadar.

Anytime. Cheers!
