### ISSUE TITLE
Problem with making new tunnel

### ISSUE THREAD

**Issue by luke2m** [boringproxy/boringproxy#47]
When I try to make a new tunnel (I have never made one before), if I select TLS Termination to server, than I get 
`Failed to get cert`.
If I select any of the other two options, I get 
`open /opt/boringproxy/.ssh/authorized_keys: no such file or directory`
How can I fix this? I'm pretty sure this is my problem. I copied my client's ssh pubkey to /opt/boringproxy/.ssh/authorized_keys , but it still won't work. The server is an Oracle cloud free instance running Ubuntu 20.04 and the client is a Raspberry Pi 3B.The server is using the systemd setup as described in the docs.

**Comment by luke2m** [comment]
Sorry, I got it working. For anyone looking at this issue, make sure to put the full domain, not just the subdomain into the web UI.

**Comment by anderspitman** [comment]
Glad you got it working. You bring up 2 good points though:

1. Docs should make it clear that the full domain is needed.
2. You should be able to override the default authorized_keys location.

I'll make a couple new issues for these.

**Comment by almereyda** [comment]
A note about the docs:

https://boringproxy.io/usage/ mentions FQDNs, but does not explain this abbreviation anywhere.

A follow up has been recorded into https://github.com/boringproxy/boringproxy.io/issues/11
