### ISSUE TITLE
Docs should make it clear full domain is necessary when creating tunnel

### ISSUE THREAD

**Issue by anderspitman** [boringproxy/boringproxy#48]

**Comment by luke2m** [comment]
I’ll work on this. Do you want it in the /docs or on the website? I think it should be under usage on boringproxy.io.

**Comment by anderspitman** [comment]
Thanks @luke2m. I agree it should be on the website, here:

https://github.com/boringproxy/boringproxy.io/blob/master/pages/index.md

Note that I just pushed a small update to that file so you might want to merge it locally before making changes.

**Comment by anderspitman** [comment]
Fixed in https://github.com/boringproxy/boringproxy.io/pull/4

**Comment by almereyda** [comment]
Sorry for hijacking this issue after it has been closed.

Would another option be to infer from domains provided as single Non-FQDNs hostnames (strings without dot), that the tunnel wants to be created as a subdomain of the admin node?

Would this be worth another issue?

**Comment by anderspitman** [comment]
@almereyda it's not a bad idea but it doesn't solve all corner cases. For example if the user's intention is a sub.sub domain they can still get unexpected behavior. I'd lean towards not implementing a special case.

I do think that eventually domains will need to be registered. This is important for multi-tenant situations to prevent people from hijacking each others' domains. If/when this is implemented, we could add a dropdown for the apex domain to make it clear what the final tunnel domain will look like. I'll create an issue that mentions this.
