### ISSUE TITLE
Client does not show up in Admin UI

### ISSUE THREAD

**Issue by almereyda** [boringproxy/boringproxy#5]
After connecting, the client does not show up in the admin UI

1. Start the server
2. Obtain credentials for the client (user, token)
3. Start the client
4. Navigate to `/#/tunnels`
5. Find client name *Any*, but none else.

The connection is established

On the server:

```
root@outpost:~/boringproxy# ss -natp | grep boringproxy
LISTEN 0      128                           *:80                        *:*      users:(("boringproxy",pid=16256,fd=9))
LISTEN 0      128                           *:443                       *:*      users:(("boringproxy",pid=16256,fd=8))
ESTAB  0      0      [::ffff:148.251.175.150]:443  [::ffff:80.187.118.30]:26887  users:(("boringproxy",pid=16256,fd=10))
```

On the client:

```
$ ss -natp | grep boringproxy
ESTAB      0       0              10.10.10.10:37936      148.251.175.151:443    users:(("boringproxy",pid=1224785,fd=3))
```

but cannot be configured to be used.

**Comment by almereyda** [comment]
The client throws a nice warning, in case the server goes down during the connection:

```
2020/11/02 15:38:41 Get "https://outpost.chn.io/api/tunnels?client-name=dmx": dial tcp 148.251.175.150:443: connect: connection refused
```

**Comment by almereyda** [comment]
The client throws a nice warning, in case the server goes down during the connection:

```
2020/11/02 15:38:41 Get "https://outpost.test.io/api/tunnels?client-name=test": dial tcp 148.251.175.151:443: connect: connection refused
```

**Comment by almereyda** [comment]
The same happens with a connection to bpdemo.brng.pro. I can establish a connection, but the client does not show up in the page for tunnels.

```
ESTAB        0        35          10.10.10.10:45514     134.209.142.119:443     users:(("boringproxy",pid=1297588,fd=7))                                       
```

**Comment by anderspitman** [comment]
This is an interesting case. I'm not sure we want to give admins control over clients running on other people's devices. If you set `-user admin` when you start the client, you should see it in the list.

**Comment by almereyda** [comment]
Ah! Indeed. For me being an administrator means that I have complete observability and control about the users of my services, because in the end it will be me who is legally responsible, in any case. Introspection into what's going on seems important to me for an elevated, priviledged maintainer view.

**Comment by anderspitman** [comment]
Let's keep the client list on the back burner, unless it becomes a priority for you where you have users and you need to be able to see their tunnels. Maybe as time goes on we'll get a clearer idea of the tradeoffs and use cases.

> Additionally, I would suggest to supply different kinds of tokens - we already have admin and user tokens. But as a user I might wish to hand out a token to one of my peers, but not have it control all my tunnels. Whyfore a guest token or similar, without access to the Web UI, comes to mind.

This is definitely planned. Eventually I'd like to have a comprehensive set of permissions, with an OAuth profile. Imagine if you could delegate control over a specific subdomain/tunnel to a third party service. A startup could host your blog for you without even having to run their own web servers.

**Comment by almereyda** [comment]
Thank you for these details. This was what I needed to know to get a connection up and running.

I will now focus to provide information about this within https://github.com/boringproxy/boringproxy.io/issues/1
