### ISSUE TITLE
.ssh/authorised_keys: no such file or directory

### ISSUE THREAD

**Issue by Zygodon** [boringproxy/boringproxy#52]
Hi @anderspitman ; **so nearly** got boringproxy working, but I get this error when setting up a tunnel: open /home/pi/.ssh/authorized_keys: no such file or directory.

This seems to resemble a similar issue raised by @arnabdafadar but that issue is closed with no account of a resolution.

The situation is thus. At the moment, everything is running on my LAN (so strictly no need for tunneling). Boringproxy server is running on a raspberry pi and I have no problem opening the boringproxy web interface to set up a tunnel.
At the same time, I have an app running on port 5000 on a second pi. In the BP web interface on the server, I can see it with the specified client name. To make a tunnel, I set up Domain as an arbitrary subdomain of my principle domain, and enter the correct port and select the client name from the drop down list.

So, on hitting submit, I get the /home/pi/.ssh/authorized_keys: no such file or directory message

Do you have any suggestion as to what might be going on here? Obviously, to get this far the SSH certificate and token have been generated successfully, and I used the token to start the BP client on the target machine running my app.

**Comment by Zygodon** [comment]
I've just noticed the submission from @luke2m  - I think that is not my problem, though, as I do specify the full domain name in Domain. But I am using an arbitrary subdomain name there. Is that correct?

**Comment by luke2m** [comment]
@Zygodon Are you running as a systemd service or directly from the shell?

**Comment by Zygodon** [comment]
Directly from shell: ./boringproxy_arm server -admin-domain thewensleyhouse.xyz

**Comment by Zygodon** [comment]
Directly from shell: ./boringproxy_arm server -admin-domain thewensleyhouse.xyz
I note that I don't have a subdomainhere. Should I have?

**Comment by arnabdafadar** [comment]
Hey @Zygodon. This is the exact issue I faced few days back. Apologies for not properly commenting before closing the issue. You may try what I did and see if it fixes your issue.

What I did was I setup a password-less authentication to my Oracle Cloud Instance (where I run my BP server).
You can try to do the same with the RaspberryPi where you run your BP server.
If you are unfamiliar with how to setup a password-less authentication, you may follow this super handy guide to setup one. 
https://tynick.com/blog/02-29-2020/how-to-create-and-use-ssh-keys-to-login-without-a-password/
In this guide, the "remote_pi" will be your Pi running the BP Server and "local_pi" will be the Pi running your web apps.) 

I am not sure if this will fix your issue, but do give it a try. This atleast fixed my issue.
In the meantime, @anderspitman might be able to tell the exact cause for this issue.

**Comment by arnabdafadar** [comment]
> Directly from shell: ./boringproxy_arm server -admin-domain thewensleyhouse.xyz
> I note that I don't have a subdomainhere. Should I have?

I don't think giving a subdomain or not will affect the tunnel.

**Comment by arnabdafadar** [comment]
> Directly from shell: ./boringproxy_arm server -admin-domain thewensleyhouse.xyz
> I note that I don't have a subdomainhere. Should I have?

On a completely different note, your 'The River Ouse Project' grabbed my attention. Will dig deep into it and will surely connect with you on that. Seems Interesting :)

**Comment by luke2m** [comment]
> What I did was I setup a password-less authentication to my Oracle Cloud Instance (where I run my BP server).
That’s what needed to do as well.

**Comment by luke2m** [comment]
> I note that I don't have a subdomainhere. Should I have?

I’m not sure, but I think that it would work as long as your DNS record is setup correctly.

**Comment by Zygodon** [comment]
Yep, that (passwordless authentication) solved my immediate problem. Thank you all for the information. There's still something else not ackling, but I'll dive into that later.

@arnabdafadar, Enjoy The River Ouse project! It's some time since I worked on it and when I had a look a couple of weeks ago, I found a few things that needed updating. I'll get round to that when - if - I've finished The Wensley House project; do contact me via the GitHub pages.

Cheers,

John

**Comment by arnabdafadar** [comment]
> Yep, that (passwordless authentication) solved my immediate problem. Thank you all for the information. There's still something else not ackling, but I'll dive into that later.
> 
> @arnabdafadar, Enjoy The River Ouse project! It's some time since I worked on it and when I had a look a couple of weeks ago, I found a few things that needed updating. I'll get round to that when - if - I've finished The Wensley House project; do contact me via the GitHub pages.
> 
> Cheers,
> 
> John

I am glad that I could be of any help. Let us know what other issues you are facing, might be able to help on that as well.
I will surely look into your projects. I find such kind of work quite interesting. Will get in touch!. Have a great day.

**Comment by anderspitman** [comment]
Oooooh I think I might know what is going on here, at least partially. Can you guys help me do a bit more testing? You shouldn't need to manually set up SSH keys for boringproxy to work, because it already generates a key for each tunnel created. It also locks that key to only be usable for creating a tunnel on that specific port, which improves security.

My theory is that you don't actually have to do any setup of passwordless login, other than creating a blank authorized_keys file. Can one of you confirm that?

PS - Thanks @arnabdafadar and @luke2m for helping out.

**Comment by arnabdafadar** [comment]
> Oooooh I think I might know what is going on here, at least partially. Can you guys help me do a bit more testing? You shouldn't need to manually set up SSH keys for boringproxy to work, because it already generates a key for each tunnel created. It also locks that key to only be usable for creating a tunnel on that specific port, which improves security.
> 
> My theory is that you don't actually have to do any setup of passwordless login, other than creating a blank `$HOME/.ssh/authorized_keys` file for the server to use. Can one of you confirm that?
> 
> PS - Thanks @arnabdafadar and @luke2m for helping out.

Hey @anderspitman. I will test this out tomorrow and will let you know the results. I will setup a fresh instance of  BP server with only a blank authorized_key file. Do you want me to provide any specific permissions or user/group access to the file (chmod/chown) to the file?

**Comment by anderspitman** [comment]
Thanks @arnabdafadar. Ideally if you could match whatever permissions the OpenSSH server uses when it creates the file itself.

**Comment by arnabdafadar** [comment]
> Thanks @arnabdafadar. Ideally if you could match whatever permissions the OpenSSH server uses when it creates the file itself.

Hi @anderspitman . So I spun up a new BP server without any password-less authentication. Created a blank 'authorized_keys' file and tried making tunnels..and voila..it worked!
I think the documentation needs to mention this as a step in the installation process or you can create a simple shell script that does this along with the other pre-requisites and deploy that with the BP script as well.

![Screenshot from 2021-02-10 11-15-28](https://user-images.githubusercontent.com/64244912/107470581-9dfd8680-6b91-11eb-945d-9f4ae1750ed4.png)

**Comment by Zygodon** [comment]
I have a different experience from @arnabdafadar. If I launch BP server with the authorized_keys file resulting from the passwordless authentication routine, I can create a tunnel, but when I open that tunnel, I get an error:
Get "http://localhost:43287/": dial tcp [::1]:43287: connect: connection refused
(and this may just be a downstream problem that needs further investigation; on the other hand it may be something to do with using incorrect keys)

Then if I rename authorized_keys, and make a new, empty authorized_keys file with touch, delete the tunnel I just made and attempt to recreate it (with the empty authorized_keys file), I cannot create the tunnel at all and I get this message:
open /home/pi/.ssh/authorized_keys: permission denied

I don't know whether this sheds light on the situation, or just muddies the water?

**Comment by luke2m** [comment]
@Zygodon when you run `ls -l`, are the permissions the same as arnabdafadar’s screenshot? (Substituting ubuntu for your username)

**Comment by arnabdafadar** [comment]
> "http://localhost:43287/": dial tcp [::1]:43287: connect: connection refused

@Zygodon Well, for the _"http://localhost:43287/": dial tcp [::1]:43287: connect: connection refused"_ error, can you please check what is it showing on your Client Pi's terminal? Is it showing Sync Tunnel along with the name of the subdomain you created? or something else?

I had a similar type of issue where I noticed that my Client was not properly connected with the server and hence the 'connection refused' error. I restarted the Client Pi, tried establishing a connection with the server, created a fresh tunnel and then it worked as expected.

**Comment by Zygodon** [comment]
Thank you @luke2m. It wasn't the permissions - I had put them right - but the owner. I expect I should not have used sudo touch to create the new file as it was owned by root. 
sudo chown pi authorized_keys did the trick:

pi@raspberrypi:~/.ssh $ sudo chown pi authorized_keys
pi@raspberrypi:~/.ssh $ ls -l
total 4
-rw------- 1 pi root    0 Feb 10 10:53 authorized_keys
-rw------- 1 pi pi   1099 Feb 10 14:15 old_authorized_keys

So now, yes, I can create the tunnel, and all that was required was an empty authorized_keys file. Now I can start to investigate why I cannot actually open the tunnel. If I can't find the answer myself, that will be a different issue.

Thanks all for your help.

**Comment by anderspitman** [comment]
> I spun up a new BP server without any password-less authentication. Created a blank 'authorized_keys' file and tried making tunnels..and voila..it worked!

Excellent, thanks!

> I think the documentation needs to mention this as a step in the installation process or you can create a simple shell script that does this along with the other pre-requisites and deploy that with the BP script as well.

I can do better than that. I'll just have the server create the file with 0600 permissions if it doesn't exist.

Thanks guys!

**Comment by arnabdafadar** [comment]
> 
> 
> > I spun up a new BP server without any password-less authentication. Created a blank 'authorized_keys' file and tried making tunnels..and voila..it worked!
> 
> Excellent, thanks!
> 
> > I think the documentation needs to mention this as a step in the installation process or you can create a simple shell script that does this along with the other pre-requisites and deploy that with the BP script as well.
> 
> I can do better than that. I'll just have the server create the file with 0600 permissions if it doesn't exist.
> 
> Thanks guys!

Perfect! That makes sense. Looking forward to a new version. Cheers :)
