### ISSUE TITLE
Invalid HTTP Error code when interacting with /users HTTP API method

### ISSUE THREAD

**Issue by OPHoperHPO** [boringproxy/boringproxy#54]
Hello,

It looks like the `/users` API method returns an invalid HTTP error code when trying to invoke it with an not allowed method. It returns a [406](https://developer.mozilla.org/en/docs/Web/HTTP/Status/406) code which means: Not Acceptable. Although it should return the code [405 - Method Not Allowed](https://developer.mozilla.org/en/docs/Web/HTTP/Status/405), as the `/tunnels` method [do it](https://github.com/boringproxy/boringproxy/blob/c3a182e9569896241f770105f2373dc559fb0ffd/api.go#L102) in the same situation.

https://github.com/boringproxy/boringproxy/blob/c3a182e9569896241f770105f2373dc559fb0ffd/api.go#L137

**Comment by anderspitman** [comment]
Yep looks like a typo. Thanks @OPHoperHPO!
