### ISSUE TITLE
Failed to dial: ssh: handshake failed

### ISSUE THREAD

**Issue by pdemacs** [boringproxy/boringproxy#59]
I am getting following error when trying it on google compute instance

boringproxy client -server example.com -token redacted -client-name demo-client -user admin
2021/02/12 16:09:54 SyncTunnels
2021/02/12 16:09:54 New tunnel test.example.com
2021/02/12 16:09:54 BoreTunnel test.example.com
2021/02/12 16:09:56 Failed to dial: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

I have set GatewayPort set to clientspecified and following everything else from the demo video

**Comment by anderspitman** [comment]
Hi @pdemacs, does $HOME/.ssh/authorized_keys file exist with 0600 permissions on the server? This is a [known bug](https://github.com/boringproxy/boringproxy/issues/53) I'll be fixing in the next release.

**Comment by anderspitman** [comment]
So I actually have another user reporting the same error, and I don't think it's authorized_keys. Can you try this:

If you click the "Download Private Key" button in the UI and use that to create an SSH tunnel manually, what happens?
You can see an example of how to do it in this script: https://github.com/boringproxy/boringproxy/blob/master/scripts/tunnel.sh

**Comment by pdemacs** [comment]
I tried it, i am not able to connect. Is it possible to supply my own private/public key pair to boringproxy which is known to be working?

**Comment by anderspitman** [comment]
It is not, and not a planned feature currently since boringproxy is designed for multi-user/multi-tenant situations where users are not intended to have general SSH access to the server.

Since you seem comfortable with SSH, you can probably find a better solution from my list here:

https://github.com/anderspitman/awesome-tunneling

If you want something minimal, I'd recommend my own SirTunnel project:

https://github.com/anderspitman/SirTunnel

If you want something with more features and production ready, check out sish:

https://github.com/antoniomika/sish

**Comment by anderspitman** [comment]
If you want to keep debugging boringproxy, can you verify that creating a plain SSH tunnel (ie ssh -R) works as expected?

**Comment by pdemacs** [comment]
yes plain ssh tunnel works fine without using boringproxy. problem is coming because handshake is failing. 
For google cloud, server is behind the firewall and to connect to it using ssh, public key needs to be uploaded to google cloud ui which then configures the server for ssh access so i am not sure if auto generation of keys by boringproxy will work out of the box that is the reason i wanted to check with @OPHoperHPO as he mentioned he was also using google cloud.
Further keys generated by boringproxy are also not working with ssh -R

**Comment by anderspitman** [comment]
Ah yes if google is intercepting the SSH that could cause problems. Have you tried generating the public keys from the private keys boringproxy gives you? You could also extract them from boringproxy_db.json. But doing all this manually kills most of the benefit of boringproxy. I think something like SirTunnel is really what you want.

It sounds like google isn't offering a true VPS that gives you control over networking.

**Comment by OPHoperHPO** [comment]
> yes plain ssh tunnel works fine without using boringproxy. problem is coming because handshake is failing. 
> For google cloud, server is behind the firewall and to connect to it using ssh, public key needs to be uploaded to google cloud ui which then configures the server for ssh access so i am not sure if auto generation of keys by boringproxy will work out of the box that is the reason i wanted to check with @OPHoperHPO as he mentioned he was also using google cloud.
> Further keys generated by boringproxy are also not working with ssh -R

I have boringproxy's automatic key generation working.

I have been used this setup for boringproxy.
1) My f1 instance uses Container Optimized OS.
2) I put boringproxy with separated openssh server to the blank alpine linux docker container. Also I set custom port for ssh server, add password to the root user (it is needed for pubkey auth.), create /root/.ssh/authorized_keys file with needed permissions, disable password authentication, and allow ports forwarding in openssh server configuration file. Finally, i run container on server and give him access to host networking. 
3) I opened all ports in the google firewall for all ips for server with boringproxy.  (You can edit firewall rules in the Google Cloud Console -> Networking -> Firewall). Also i have been rent static ip for this server.

**Comment by anderspitman** [comment]
Thanks @OPHoperHPO!

> ...create /root/.ssh/authorized_keys file with needed permissions...

Note that the latest release of boringproxy (v0.6.0, released a few hours ago) should handle this automatically.

**Comment by pdemacs** [comment]
hmm, i am doing evrything that you have done except docker container, i am running directly on f1. I am not familiar with docker tooling so i guess i have to look for something else, anyways thanks @anderspitman @OPHoperHPO for helping out.

**Comment by techiezia** [comment]
@OPHoperHPO Can you please give more details/detailed instructions of running boringproxy on f1 insatnce.

**Comment by k4ml** [comment]
I have this same problem and after hours of troubleshooting, it turns out caused by old openssh version that doesn't have permitlisten support. If you look in server's log, you will see something like this:-

```
sshd[815]: Bad options in /home/ubuntu/.ssh/authorized_keys file, line 19: permitlisten="127.0.0.1:34285" ssh-rsa
```

And this is from openssh changelogs:-

```
Changes since OpenSSH 7.7
=========================

This is primarily a bugfix release.

New Features
------------

 ...

 * sshd(8): add a PermitListen directive to sshd_config(5) and a 
   corresponding permitlisten= authorized_keys option that control
   which listen addresses and port numbers may be used by remote
   forwarding (ssh -R ...).
```

https://www.openssh.com/txt/release-7.8

After upgrading to ubuntu 20.04 with openssh 8.2 the error went away. Maybe add in the docs somewhere minimum openssh version require.
