### ISSUE TITLE
Another connection refused issue

### ISSUE THREAD

**Issue by Zygodon** [boringproxy/boringproxy#60]
This looks similar to issue #21 from @pentagon98: I have created a tunnel like:
camera.twh.xxx:36563 -> any -> 127.0.0.1:5000

On going to the link I get the connection refused error:

Get "http://localhost:36563/": dial tcp [::1]:36563: connect: connection refused

Unlike @pentagon98, my server and client are on different machines, both on my domestic lan. Even so, I suspect that the issue is the same, port forwarding 22. My understanding is that I would need to do this for the server?

My difficulty is that other machines on my network are also using port 22, so I need to forward something like 2200 -> 22. Is there a way that I can get borinproxy to recognise this? I understand that, if I am correct in my analysis of the situation, this is not truly a boringproxy issue - but I would be very glad to have some advice.

Maybe, though, my understanding is not right because since writing the above, I've temporarily undone the port forwarding on the other machines and forwarded port 22 on the server to port 22 on the router, but I still get the same message and the connection is refused (as a check, on the client terminal when boringproxy client starts, I do get SyncTunnels)

**Comment by Zygodon** [comment]
Further possibly useful information:
on the server terminal I'm seeing "2021/02/12 16:01:39 http: TLS handshake error from 178.136.243.144:54659: no certificate available for 'twh.xxx'" - which is odd because I've not used the unqualified domain name at all (ie without a preceding subdomain);

and on the client terminal I'm seeing

2021/02/12 16:01:56 SyncTunnels
2021/02/12 16:01:56 New tunnel camera.twh.xxx
2021/02/12 16:01:56 BoreTunnel camera.twh.xxx
2021/02/12 16:01:56 Failed to dial: dial tcp 86.144.XXX.YYY:22: connect: connection refused.

Does this help? I note the reference to port 22 on my redacted public IP address

**Comment by OPHoperHPO** [comment]
@Zygodon 
> My difficulty is that other machines on my network are also using port 22, so I need to forward something like 2200 -> 22. Is there a way that I can get borinproxy to recognise this?

boringproxy server has a -ssh-server-port option to specify a different ssh server port. It will send this port to clients to connect.

**Comment by OPHoperHPO** [comment]
@Zygodon  Is port 22 on your public ip address open for the server?  It looks like port 22 is closed on your public address. Try to check it with this tool. https://sshcheck.com/

**Comment by Zygodon** [comment]
Thanks, @OPHoperHPO . Yes, I used sshcheck.com as you advised - port 22 is open and the server is the rasbpian server as expected with the port forwarding from the Raspberry Pi that I'm using as my boringproxy server. That's really interesting. I definitely neeed to think my way through this - as far as I can tell, boringproxy is functioning as advertised; I probably need a better in depth knowlege of SSH.

A thought is troubling me. Here's the set up: for development, I have two Raspis on my local domestic LAN. One is the BP server, the other the BP client running an app to deliver images on demand to a remote browser (in deployment, this will be in a distant location and will communicate on 3G). The BP server has a monitor. The client is headless. I'm SSHing into the client from the server to get a terminal to control it from - that is, to start the BP server. Am I over using SSH here? So, I will try to check this using hot switching of the monitor.

I will also check out the -ssh-server-port option.

And maybe the f1-micro Compute Engine you mentioned could be useful to me. My horizons are expanding. Thanks to all community members who are helping me through this. Much appreciated.

**Comment by pdemacs** [comment]
@OPHoperHPO , can you give more details on how you are able to use boringproxy on f1-instance . I am trying the same and i am getting failed to dial: ssh: https://github.com/boringproxy/boringproxy/issues/59 . I am suspecting it is google firewall issue rather than boringproxy issue but not sure about the right configuration. If by any chance you have any writeup can you point me to it?

**Comment by anderspitman** [comment]
@Zygodon one other thing you might try just looking at your configuration. If you're using a client, you pretty much never want to set "Client" to "Any". That option is poorly named. It should say "None", because it means no clients will be able to service that tunnel.

You may be wondering why that's even an option. The reason is because it's useful for cases when you're running the boringproxy server on the same machine as your service. It essentially lets you use boringproxy like a normal reverse proxy, skipping the tunneling functionality.

**Comment by anderspitman** [comment]
Going to close this for now. Feel free to reopen.
