### ISSUE TITLE
Tunnels list does not reflect the complete configuration of a tunnel

### ISSUE THREAD

**Issue by almereyda** [boringproxy/boringproxy#63]
As a boringproxy user, I want to quickly glance over configured tunnels, in order to distinguish their configuration visually.

Currently a tunnel, like

    garten.outpost.chn.io:33421 -> ex -> garten.hof.pause:80 

displays:

- Tunnel source domain
- Tunnel port on Server node
- Name of client
- Proxy target domain or IP as seen from Client  
- Proxy target port

This display lacks available information about other configuration options, with little more possibly to come, like

- Allow External TCP,
- Password Protect and
- TLS Termination.

While the first two are simple booleans that can be represented with disabled checkboxes or ☐ and ☒ or 🗵 or ⮽, the TLS Termination could be represented with a lock 🔒 that is either placed before the source (Server), the Client or the target (passthrough).

To gain screen estate, the download and delete buttons can also be reduced to Unicode symbols, when wanting to avoid additional icon fonts.

Download

- ⭳
- ⤓
- 🡇

Delete

- −
- ➖
- 🗑

**Comment by anderspitman** [comment]
I'm definitely keen to improve this. Sad said, I'm trying to move away from putting symbols in my UIs. They look cool and save space, but half the time you have to hover over them to know what they mean in the given context, which isn't even possible on mobile.

So I'd prefer a text-only solution if possible.

**Comment by anderspitman** [comment]
I admit this is a controversial idea, but I consider it something of an experiment as well to see if it can work.

**Comment by anderspitman** [comment]
In concrete terms, I think it might be appropriate to move some of the boringproxy information to a separate screen/popup. For example I don't think the private key or delete buttons need to be glanceable.

So if you were to list the items in descending importance, how would you rank them?

**Comment by anderspitman** [comment]
This is greatly improve as of v0.8.1. Should be sufficient detail.
