### ISSUE TITLE
Server failing to obtain a certificate (again)

### ISSUE THREAD

**Issue by Zygodon** [boringproxy/boringproxy#65]
I do apologise for what must surely be some oversight on my part, but right now this is driving me crazy. I have not so far been able to create a functioning tunnel with boringproxy, but last week I was at least able to start the server. But now I am again stuck with failure to obtain a certificate. In frustration, I have done a complete, clean reinstall of the raspberry Pi OS so there's no nginx or anything like that to get in the way.
I have enabled SSH and have OpenSSH version 7.9.
I have checked the A+DDNS records on my domain with Namecheap:

A + Dynamic DNS Record | * | 127.0.0.1 | Automatic
A + Dynamic DNS Record | @ | 127.0.0.1 | Automatic

I have installed firewall ufw and opened ports:
 $ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere                  
22/tcp                     ALLOW       Anywhere                  
2200                       ALLOW       Anywhere                  
80                         ALLOW       Anywhere                  
443                        ALLOW       Anywhere                  
22 (v6)                    ALLOW       Anywhere (v6)             
22/tcp (v6)                ALLOW       Anywhere (v6)             
2200 (v6)                  ALLOW       Anywhere (v6)             
80 (v6)                    ALLOW       Anywhere (v6)             
443 (v6)                   ALLOW       Anywhere (v6)  

I have set up appropriate port forwarding on my router, specifically, 80, 443 and 2200 for the new IP address of the Raspberry Pi (with the newly flashed OS)    

I have downloaded boringproxy-linux-arm, done the chmod +x and setcap.

I have made folder .ssh in my home directory and touched an empty authorized_keys file and set permissions to 600.

I start the server using ssh port 2200 to avoid confusion with other machines on my home network which could also use port 22. Added in edit: I have set the port in sshd_config to 2200, and restarted the service):
$ ./boringproxy-linux-arm server -ssh-server-port 2200 
and give it an appropriate Admin Domain (admin.mydomainname.xxx) and, on first run, my email address; and I get:
 no solvers available for remaining challenges (configured=[tls-alpn-01] offered=[http-01 dns-01 tls-alpn-01] remaining=[http-01 dns-01]) (order=https://acme-v02.api.letsencrypt.org/acme/order/112839143/7924929173) (ca=https://acme-v02.api.letsencrypt.org/directory)

Thanks @OPHoperHPO for suggesting sshcheck.com in connection with getting the client running: I have checked with that and the port 2200 is open.

Which is really back to square 1.
Please can some kind person out there check through this lot? I can't see that I've overlooked anything. And if I haven't then what is going wrong? ANY suggestion about what further checks I can make will be most welcome.

@zygodon

**Comment by Zygodon** [comment]
I have discovered my problem - but I would like to leave this note here in case it would be useful to any other ignoramus trying to negotiate the smoke and mirrors world of ssh tunneling. My problem was that the Namecheap DDNS client was not configured properly and so was not updating my DDNS records properly - which, had I understood more, I would have seen must be the case from the IP address in the records. For anybody who needs to know: there is an insignificant check box which needs to be checked for the DDNS client to auto detect the public IP address. My word. I thought that was the whole point!

Again, thanks to the community for support and I look forward to making progress again.

@zygodon

**Comment by Zygodon** [comment]
I intended to push the Close button ...

**Comment by anderspitman** [comment]
@Zygodon for what it's worth, DNS is a lot harder to use than it should be. We need higher level services that make it as easy to by and use a domain name as it is for phone numbers. This is something I'm planning on working on related to my work with boringproxy.

**Comment by Zygodon** [comment]
Hi @anderspitman , I'm with you there, and I understand what you are trying to achieve with boringproxy. In fact, one of the reasons I chose boringproxy was precisely your stated aim of providing a higher level service for relatively ignorant users like me. I think you have gone a long way towards it, and I really appreciate the work you have put into it.

I would like to offer help. But I think all I can offer really is to be a typical ignorant user, which I guess is your target audience. If I can help in that capacity, let me know. Maybe I could work on the documentation?

Cheers, @Zygodon

**Comment by anderspitman** [comment]
@Zygodon honestly just sticking with it and being patient is helpful. As long as you understand boringproxy is beta software and I'm mostly designing it for my own uses (though I'm happy if it's helpful for others), I appreciate the feedback.

We're trying to get started with a wiki for users to document what they've gotten working and the steps necessary. You can chime in on #61 if you'd like to help out. Thanks!
