### ISSUE TITLE
Typo on installation page breaks download for amd64

### ISSUE THREAD

**Issue by lightnin** [boringproxy/boringproxy#67]
Trailing "d" on the "curl" command is incorrect. 
<img width="770" alt="Screenshot 2021-02-18 at 08 43 32" src="https://user-images.githubusercontent.com/1538027/108322307-9a878200-71c5-11eb-83eb-a796ffc91726.png">
(Would have submitted a PR, but couldn't see just where the code for the install page is...)

**Comment by anderspitman** [comment]
Thanks @lightnin; should be fixed now.
