### ISSUE TITLE
Need to protect against authorized_keys file getting too big

### ISSUE THREAD

**Issue by anderspitman** [boringproxy/boringproxy#70]
Mine is currently at 5.4GB somehow, which is causing the creation of new tunnels to hang and eventually crash the server by trying to load the file into memory.

Not sure what originally caused this but there should be safeguards against it.

**Comment by carlostkd** [comment]
changing the ssh port to another than 22  on the sshd,conf and starting the boring proxy specifying the right port on the server command solves this issue.

**Comment by darrynhoskingluna** [comment]
I can confirm that i am also expereincing this issue. 

@carlostkd could you elaborate further on that changing of the ssh port, is that just for boring proxy or the server as a whole?
Fyi i am running an ec2 instance on aws and hosting it there.

**Comment by carlostkd** [comment]
> I can confirm that i am also expereincing this issue.
> 
> @carlostkd could you elaborate further on that changing of the ssh port, is that just for boring proxy or the server as a whole?
> Fyi i am running an ec2 instance on aws and hosting it there.

Hi, when you change the port then its for the whole ssh server.
