### ISSUE TITLE
Same client address and ssh error

### ISSUE THREAD

**Issue by Ataraxiall** [boringproxy/boringproxy#71]
Good Morning,

I am testing the program, but I have noticed that the client's ip in the "client Address" menu is always 127.0.0.1. Shouldn't it be the client's ip selected in the menu?

On the other hand, I get this error in the windows version.
BoreTunnel error:  Failed to dial: %!(EXTRA *errors.errorString=ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)

Thanks in advanced!!

**Comment by Ataraxiall** [comment]
I can see this in ssh log

Bad options in /root/.ssh/authorized_keys file, line 1: permitlisten="127.0.0.1:36299" ssh-rsa "numberhere"

**Comment by anderspitman** [comment]
Hi @Ataraxiall, boringproxy requires version 7.8+ (that's when permitlisten was added). permitlisten is a security feature to ensure a given private key can only open tunnels on a specific port. This isn't so important if you're the only user on your server (which is likely), but there's not currently a way to disable it, and it's not planned.

If you want to self-host a simple single-user tunnel proxy, I'd recommend you take a look at [SirTunnel](https://github.com/anderspitman/SirTunnel), or check my list [here](https://github.com/anderspitman/awesome-tunneling) for other projects.

**Comment by Ataraxiall** [comment]
Thanks a lot!

I have updated it and now it works great!

Thanks!
