### ISSUE TITLE
Can it be available to FreeBSD?

### ISSUE THREAD

**Issue by tjsas1** [boringproxy/boringproxy#74]
Hi Can it be available to FreeBSD?

**Comment by anderspitman** [comment]
Hi @tjsas1. Should be possible, but a developer who uses FreeBSD will have to set it up. I don't have time.

**Comment by anderspitman** [comment]
Hi @tjsas1, release v0.7.0 includes builds for FreeBSD and OpenBSD. They are untested, but may work.
