### ISSUE TITLE
Error when creating tunnel

### ISSUE THREAD

**Issue by smallstech** [boringproxy/boringproxy#75]
When creating a tunnel the client crashes with this error message (on ubuntu 20.04 clean install besides docker)

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/boringproxy/boringproxy.(*Client).PollTunnels(0xc00017ed80, 0xaf8060, 0xc000024088, 0x0, 0x0)
        /home/anders/code/boringproxy/client.go:169 +0x68e
github.com/boringproxy/boringproxy.(*Client).Run(0xc00017ed80, 0xaf8060, 0xc000024088, 0x0, 0x0)
        /home/anders/code/boringproxy/client.go:130 +0x252
main.main()
        /home/anders/code/boringproxy/cmd/boringproxy/main.go:85 +0x88b
```

**Comment by smallstech** [comment]
Forgot to run `setcap cap_net_bind_service=+ep boringproxy-linux-x86_64` after moving file.

**Comment by anderspitman** [comment]
@smallstech you're saying you needed to run setcap on the client executable? It should only be required for the server.

**Comment by smallstech** [comment]
Hi, realised that wasn't the fix I think my mistake was when I made a service file on the server and forgot to set WorkingDir so it wasn't saving to the config json file. Working fine now though,
