### ISSUE TITLE
Error when using docker-compose

### ISSUE THREAD

**Issue by nickshanks347** [boringproxy/boringproxy#77]
When running `docker-compose up`:
```
Building boringproxy
Sending build context to Docker daemon  141.3kB

Step 1/14 : FROM golang:1.15-alpine3.12 as builder
 ---> 8b72cb43d5db
Step 2/14 : WORKDIR /build
 ---> Using cache
 ---> 50de56f044d9
Step 3/14 : RUN apk add git
 ---> Using cache
 ---> 47e5db44efc6
Step 4/14 : RUN go get github.com/GeertJohan/go.rice/rice
 ---> Using cache
 ---> 150a807f1594
Step 5/14 : COPY go.* ./
 ---> Using cache
 ---> 4ac6ff036f13
Step 6/14 : RUN go mod download
 ---> Using cache
 ---> 56712b41a42e
Step 7/14 : COPY . .
 ---> Using cache
 ---> 802cee3e848d
Step 8/14 : RUN rice embed-go
 ---> Using cache
 ---> f64fe5433fc4
Step 9/14 : RUN CGO_ENABLED=0 go build
 ---> Using cache
 ---> b59657560c44
Step 10/14 : FROM scratch
 --->
Step 11/14 : EXPOSE 80 443
 ---> Using cache
 ---> eeccb02e5a55
Step 12/14 : COPY --from=builder /build/boringproxy /
COPY failed: stat build/boringproxy: file does not exist
ERROR: Service 'boringproxy' failed to build
```

I'd like to use docker so it's easier to map the WebUI to different ports because I already have things running on 80 and 443. In the directory I'm in (git clone of this repo), there is no build directory so I'm not surprised it's failing but not sure what I need to do in order to get the build directory with the correct files.

**Comment by nickshanks347** [comment]
I just copied the `build_x86_64.sh` to the root git repo and ran it. I get a build directory but the error still occurs, even after I rename the file to `boringproxy/build/boringproxy`.

**Comment by nickshanks347** [comment]
Tagging in @fbartels because he submitted the PR for Docker.

**Comment by fbartels** [comment]
> In the directory I'm in (git clone of this repo), there is no build directory so I'm not surprised it's failing

the "build" directory comes from the `workdir` setting in the Dockerfile at https://github.com/boringproxy/boringproxy/blob/bab13efdbf88b664f75b12d4d37aa1db36b381a0/Dockerfile#L3

The reason for the build failing is that a `gp build` no longer creates a file called `boringproxy`. Easy solution is to force the name for the binary, as done in #78.

I have not dissected the changes over the last month to exactly identify when it broke, nor have I deployed this project somewhere, so there could be better fixes to this problem.

**Comment by anderspitman** [comment]
@nickshanks347 I've merged @fbartels pull request with the fix. Please let me know if this fixes your problem. Unfortunately I don't use docker for boringproxy myself, so I can only provide limited assistance.

**Comment by nickshanks347** [comment]
Thanks for the help @fbartels and @anderspitman but nowI get a different error. It seems to successfully build but on `docker-compose up`:

```
docker-compose up
Creating network "boringproxy_default" with the default driver
Creating boringproxy_boringproxy_1 ... done
Attaching to boringproxy_boringproxy_1
boringproxy_1  | standard_init_linux.go:211: exec user process caused "exec format error"
boringproxy_boringproxy_1 exited with code 1
```

If you need anymore info, please let me know.

**Comment by nickshanks347** [comment]
After some more research, seems like an architecture issue. I'm running Ubuntu Server 64-bit. Also tried on a Pi though, didn't work either.

**Comment by nickshanks347** [comment]
Made a new ticket #80 because this was resolved/closed.
