### ISSUE TITLE
Reverse proxy Swagger redirects

### ISSUE THREAD

**Issue by darrynhoskingluna** [boringproxy/boringproxy#79]
When running the boring proxy and setting up a reverse proxy for a website hosting Swagger navigating to the URL will cause a redirect to 127.0.0.1:{port}.
If i use Ngrok it does not exibit the same behavior.

This seems to be a common issue when running swagger behind reverse proxys
(perhaps these seperate issues might provide some insight) 
https://github.com/noirbizarre/flask-restplus/issues/223
https://github.com/zalando/connexion/issues/887

I suspect there are some forwarding headers (X-Forwarded-For, X-Scheme & X-Forwarded-Path) that are not being passed through which causes the Swagger to generate a redirect.

**Comment by anderspitman** [comment]
Hi @darrynhoskingluna, your diagnoses is probably correct. See also #13. If you can determine a complete list of the headers missing, that will help improve the quality of the fix when I finally have time to implement it. As it is, I don't know when I'll get to it though.

**Comment by anderspitman** [comment]
Closing in favor of #13.
