### ISSUE TITLE
background

### ISSUE THREAD

**Issue by carlostkd** [boringproxy/boringproxy#82]
Tried everything that i know and i dont release how can we run the server in background?  with screen works but then we have one more process in bg.

Thanks in advanced

**Comment by anderspitman** [comment]
It shouldn't be any different than any other program. Can you provide more details about what you're trying?

Some users contributed systemd files a while back which may be useful to you:

https://github.com/boringproxy/boringproxy/tree/master/systemd

**Comment by anderspitman** [comment]
Closing for now feel free to reopen if you have further questions.
