### ISSUE TITLE
server killed

### ISSUE THREAD

**Issue by carlostkd** [boringproxy/boringproxy#83]
Hi , boringproxy was running boring and smoothly yesterday with 2 clients , then i tried to add another client the server was killed , first i was thinking maybe there is a number of connections limit , then i deleted one connection and tried again but no luck , server killed, then i started from fresh ;
setcap -r boringproxy-xxxxxx 
deleted boringproxy.json
deleted boringproxy-xxxxxx

curl again boringproxy
chmod +x
setcap settings

aquire certificate and runs nicely , clients can connect without problems , but when i try to add a tunnel , on the terminal prints only "killed"  
since there is no logs and no more info prints on the terminal someone know what ca be the problem??
now it`s really boring......... to get this works

**Comment by Minipada** [comment]
I am having the same issue. I tried running the application with GDB, by recompiling myself with the latest commit.
Running it as a standard user didn't work (port 80 was not authorized), even though I set the setcap to gdb and the new binary.
So I ran it as root, and it's working fine now (but only as root). I don't know why though.

**Comment by carlostkd** [comment]
Humm thanks anyway i tried running both as root client and server, but the same error, the server prints "killed" and client prints connection to server ip:443 connection refused. i have disabled all firewalls also tried with client on a dmz zone but no luck.

**Comment by anderspitman** [comment]
Interesting, thanks for the report. Can you monitor your memory usage (with htop or whatever you prefer)? I suspect there's a memory leak causing the server to run out of memory and kill boringproxy.

**Comment by carlostkd** [comment]
well after battle all the day with this error , i solved then by changing the server ip.
really dont know if it*s a boringproxy bug or for some reason my router have blocked the old ip due the large among of traffic?? i need take a look on the logs more carefully in the mean time if someone are experiencing  this error please change the server ip addr.

**Comment by Minipada** [comment]
> Interesting, thanks for the report. Can you monitor your memory usage (with htop or whatever you prefer)? I suspect there's a memory leak causing the server to run out of memory and kill boringproxy.

I just monitored the memory and it seems like it. I am using a t2.micro AWS EC2 machine. Before creating a tunnel, the memory is at 245M/979M.
When starting, it jumps to 400,600,850 and dies. I switched to an instance with 2 GB of memory and it worked.
When starting a second tunnel, it crashed once again. It seems boringproxy requires 1Gb of memory PER active tunnel. This is...a lot. I was planning on using at scale, but I might need to wait future versions.
@anderspitman do you know what requires so much? I would be happy to contribute, and it would be great if you could give a hint on where to start.

**Comment by carlostkd** [comment]
Hello i have installed the boringproxy alone on a clean and basic vps instance just for this memory test, the vps as only 512MB memory currently as 3  tunnels running smoothly and i have no problems with memory see the screenshoot.
hope that helps

![proxy](https://user-images.githubusercontent.com/11921177/115348630-5d7a4480-a1a2-11eb-9c3f-7bc21da08d6d.png)

**Comment by Minipada** [comment]
Oh wow. Look at mine. Same setup as yesterday evening when I wrote, but now I can't start one tunnel without it being killed.
This is the memory spike before it gets killed.

![image](https://user-images.githubusercontent.com/1220912/115351114-46c8f300-a18c-11eb-80b9-74a59260896a.png)

**Comment by carlostkd** [comment]
wtf... well maybe it depends from what kind of server are running trough the tunnel?
currently im serving a instance of  "searx" another witht "libreddit" and another with "cryptpad."

**Comment by Minipada** [comment]
I'm on AWS EC2 t2.micro for the server. The client is on manjaro

**Comment by Minipada** [comment]
I tried adding swap. I managed to start a tunnel (this time, using almost 2Go of ram)

Then, guess what, opening a second one (on the same client) resulted in similar results, it got killed again. This time I got a **peekClientHello** error though. Maybe that helps

![image](https://user-images.githubusercontent.com/1220912/115384239-19556700-a1d7-11eb-9e59-bdb2501bee85.png)

**Comment by carlostkd** [comment]
so... after experiencing connections errors again, "server killed" i have changed to another tunnel "frpc" still dont realize on to enable the ssl but at least runs well, i will give a try on the boringproxy on new realeases.

**Comment by Ataraxiall** [comment]
same error, if i delete autorized_key file in .ssh it works again

**Comment by carlostkd** [comment]
> same error, if i delete autorized_key file in .ssh it works again

Hi thanks for this however i tried this and now i get invalid domain parameter no matters what name i try to give to the subdomain.

**Comment by Minipada** [comment]
@anderspitman In case that helps, my authorized_keys file on my tunnel server has 2162688 lines. I don't know the reason, I have nothing else running on it.

**Comment by 3crow** [comment]
same issue here.
for time being fixed with

cp authorized_keys authorized_keys.bak
sort authorized_keys   | uniq > authorized_keys

**Comment by carlostkd** [comment]
> same issue here. for time being fixed with
> 
> cp authorized_keys authorized_keys.bak sort authorized_keys | uniq > authorized_keys
> 
> Original was 360 meg 1.4K Jan 22 11:53 authorized_keys 360M Jan 22 11:51 authorized_keys.bak

Glad to hear it works for you now, if that helps since i run the proxy in another port than 22  over 1000 it runs always flawless.

**Comment by 3crow** [comment]
> Glad to hear it works for you now, if that helps since i run the proxy in another port than 22 over 1000 it runs always flawless.

Thanks - were is this configured?

in boringproxy_db.json I see "server_port": 22  - can this just be edited?
or is there an option when starting borign proxy?
or does sshd need started on a high port?

As a workaround I've just added a cron job to clear out the keys file each day.

**Comment by carlostkd** [comment]
> > Glad to hear it works for you now, if that helps since i run the proxy in another port than 22 over 1000 it runs always flawless.
> 
> Thanks - were is this configured?
> 
> in boringproxy_db.json I see "server_port": 22 - can this just be edited? or is there an option when starting borign proxy? or does sshd need started on a high port?
> 
> As a workaround I've just added a cron job to clear out the keys file each day.

Hi, no no
you need to edit the ssh server port on your /etc/ssh/ssh.config or depend your system sshd.conf

then restart:   sudo service sshd restart

afther that start the proxy client and the server like this:

(i changed my boringproxy executable to proxy to be more simple, and less boring )

CLIENT
./proxy client  -server your.server.domain -user admin -token your.token -client-name anyname  &> /dev/null &

SERVER
./proxy server -admin-domain  your.domain  -ssh-server-port 1337 &> /dev/null &

cheers

**Comment by 3crow** [comment]
@carlostkd Thanks for that. Makes sense now I think about it. Getting off 22 will also slow down the multiple attempts from other large countries!
