### ISSUE TITLE
boringproxy.io account request POST fails

### ISSUE THREAD

**Issue by jay-frosen** [boringproxy/boringproxy#87]
https://demo-signup.boringproxy.io/request
Post "http://localhost:44221/request": EOF

Failed to load resource: the server responded with a status of 502 ()

Is it possible to request an account?
Thanks!

**Comment by anderspitman** [comment]
Hey @jay-frosen, the demo signup should be back now. Thanks for the heads up.

**Comment by Kamikadze4GAME** [comment]
Hello @anderspitman !

There is similar issue now. Could you check?

**Comment by anderspitman** [comment]
@Kamikadze4GAME working now?

**Comment by Kamikadze4GAME** [comment]
@anderspitman , yes! Thank you for your time and this amazing project

**Comment by anderspitman** [comment]
@Kamikadze4GAME no problem thanks for the heads up!
