### ISSUE TITLE
Configure to access RDP

### ISSUE THREAD

**Issue by MANKUD** [boringproxy/boringproxy#89]
Hello,

Could you tell me how to configure it to make it work with RDP as I cannot do it and in your demo video you did not specify clearly what needs to be done at the end.

**Comment by MANKUD** [comment]
![image](https://user-images.githubusercontent.com/83474708/125439096-fbbb00a0-93c8-45af-abf1-d44f87568c09.png)

![image](https://user-images.githubusercontent.com/83474708/125439158-a75101d5-00f0-4da9-8c1b-670ef227e792.png)

allow external TCP checked but still, RDP seems to be not working.

**Comment by anderspitman** [comment]
Hey @MANKUD it looks like your `gatewayports` setting is correct, but still commented, which means it won't have any effect. You need to remove the "#" at the beginning of the line.

**Comment by MANKUD** [comment]
Hello, thanks for the response actually I have removed the comment and tried but it did not help I forgot to attach the screenshot where the comment is removed.

**Comment by MANKUD** [comment]
![image](https://user-images.githubusercontent.com/83474708/125490881-53908224-c471-4952-b467-b39dada35b84.png)

![image](https://user-images.githubusercontent.com/83474708/125491189-23153fe9-7174-4046-8675-8779be8ab7dc.png)

![image](https://user-images.githubusercontent.com/83474708/125491214-824e7fac-df1b-491a-9706-805695c881c0.png)

![image](https://user-images.githubusercontent.com/83474708/125491260-3371a0d0-ebf0-4094-aac6-8f9f163783f4.png)

**Comment by anderspitman** [comment]
Did you reset your ssh server (sshd) after making the change? If so, I'm not sure what the problem is. I don't use RDP myself, but maybe someone else has managed to get it working with boringproxy.

If you already know how to get RDP working through SSH tunnels and just want an easy way to manage the TLS certs, take a look at [SirTunnel](https://github.com/anderspitman/SirTunnel). It's a more manual process but also easier to debug since it's just OpenSSH+Caddy.

**Comment by MANKUD** [comment]
Yes I have restarted the SSH service using (sudo systemctl restart ssh.service) but did not help anyway thanks for your time.

**Comment by MANKUD** [comment]
Hi BTW the port used for web seems to be open but RDP seems to be always closed any suggestion?

![image](https://user-images.githubusercontent.com/83474708/125496366-c03eb77a-2bb9-4943-93e6-b33b8560c454.png)

![image](https://user-images.githubusercontent.com/83474708/125496384-c76d3333-cfb7-441d-807b-fb841b3fbda3.png)

![image](https://user-images.githubusercontent.com/83474708/125496446-7f5b717f-0f87-44dc-aa04-59fdfecafda6.png)

**Comment by MANKUD** [comment]
![image](https://user-images.githubusercontent.com/83474708/125496967-59376ca8-8b61-4315-a463-dbdbb9f11a38.png)

**Comment by anderspitman** [comment]
I don't think that would have anything to do with boringproxy. You'd have to check the firewall settings on your server/VPS provider.

**Comment by MANKUD** [comment]
my UFW firewall on ubuntu is disabled and ISP is on DMZ.

**Comment by anderspitman** [comment]
Are you able to access a generic server on that port? For example:

```
python3 -m http.server 35075
```

**Comment by MANKUD** [comment]
Strange when I manually assigned port 2255 to port 3389 it seems to be working but the default random port does not seem to be working.

![image](https://user-images.githubusercontent.com/83474708/125497815-d507ce81-b65c-48b5-a963-062c04133321.png)

![image](https://user-images.githubusercontent.com/83474708/125497849-2e17501b-6538-40c3-9b2c-c545a068c7ce.png)

![image](https://user-images.githubusercontent.com/83474708/125497968-a7133cc6-9dbd-4049-b4f1-63d08d6e3d12.png)

**Comment by MANKUD** [comment]
Hi finally I got it working, I really appreciate your efforts in making this. Is there any way to automate this so that executable can be set to auto-start on windows startup along with the required parameters. BTW all the data will be passing through the boringproxy server right? so we will need enough bandwidth to run this on the boringproxy server.

**Comment by MANKUD** [comment]
Trying to configure on a new server getting this error.

![image](https://user-images.githubusercontent.com/83474708/125578118-6006b1cc-ec39-4747-8b07-2061728bb4d9.png)

**Comment by anderspitman** [comment]
Hey @MANKUD sorry for the late reply. It should be possible to automate on window startup, but I haven't used windows in years so not sure how to do that.

And yes all the data will pass through the boringproxy server. Hopefully someday we'll all be switched to IPv6 and get rid of NAT so none of this is necessary, but for now I think it's the best way.
