### ISSUE TITLE
Can't understand Documentation

### ISSUE THREAD

**Issue by testatskool** [boringproxy/boringproxy#90]
Trying to setup server on my parrot os

$ ./boringproxy-linux-x86_64 server -admin-domain penskoolskull.bpdemo.brng.pro
2021/07/25 07:25:29 Starting up
2021/07/25 07:25:35 penskoolskull.bpdemo.brng.pro: obtaining certificate: [penskoolskull.bpdemo.brng.pro] Obtain: [penskoolskull.bpdemo.brng.pro] solving challenges: penskoolskull.bpdemo.brng.pro: no solvers available for remaining challenges (configured=[tls-alpn-01] offered=[http-01 dns-01 tls-alpn-01] remaining=[http-01 dns-01]) (order=https://acme-v02.api.letsencrypt.org/acme/order/135505371/11990717921) (ca=https://acme-v02.api.letsencrypt.org/directory)

can anyone help to setupmy server !!

**Comment by anderspitman** [comment]
Hey @testatskool it looks like you're trying to run your own server, but using a domain you don't control. You'll need to understand how DNS works in order to use boringproxy effectively. If you want something simpler I'd recommend using ngrok or CloudFlare Tunnel.
