### ISSUE TITLE
How to  random Allow UDP Port corresponding to Webrtc connections to subdomains

### ISSUE THREAD

**Issue by manjurajv** [boringproxy/boringproxy#91]
How to allow WebRtc Streams coming on Random UDP ports tunneled properly?

**Comment by anderspitman** [comment]
Hi @manjurajv, unfortunately since boringproxy is built on SSH it doesn't support UDP. I'd recommend checking some of the other solutions here: https://github.com/anderspitman/awesome-tunneling

**Comment by manjurajv** [comment]
The pointed link was helpful @anderspitman
