### ISSUE TITLE
Can I have boring Proxy running on NATed IP with Portforwarding Enabled?

### ISSUE THREAD

**Issue by manjurajv** [boringproxy/boringproxy#92]
Hi @anderspitman 

My topoloty is as below

-----WAN-> [public ip] WifiRotuer [private NATed IP] <---------------> [192.168.1.3] My PC (boringproxy is running here)

It successfully ran(got certs and the WebGui too is working), but when I tried to connect the client to the proxy server it is getting me this error

````
~ : $ sudo boringproxy server -admin-domain proxy.mydomain.com
2021/08/04 15:22:59 Starting up
2021/08/04 15:23:00 Successfully acquired admin certificate
2021/08/04 15:23:00 failed reading boringproxy_db.json
2021/08/04 15:23:00 Admin token: aaaabbbbcccccddddd
2021/08/04 15:23:00 Admin login link: https://proxy.cenmeet.com/login?access_token=aaaabbbbcccccddddd

2021/08/04 16:29:44 http: TLS handshake error from 223.186.98.136:3286: no certificate available for '192.168.1.3'
2021/08/04 16:29:45 http: TLS handshake error from 223.186.98.136:3287: no certificate available for '192.168.1.3'
2021/08/04 16:29:45 http: TLS handshake error from 223.186.98.136:3288: no certificate available for '192.168.1.3'
````
How to resolve this issue.  Is mandatory that I must Public IP on my PC interface. Is there any workaround with Port forwarding at Router?

**Comment by anderspitman** [comment]
Hey @manjurajv, port forwarding should be fine. Technically that's no longer NAT so you can consider it as a public IP. I think you accidentally left your real domain in your comment (you may want to edit and remove that). I just tried accessing it and it gets me to the login page, so it actually looks like you're really close to getting this working.

Can you share the command you're using to run the client (obviously with your domain and token set to *******)?

**Comment by anderspitman** [comment]
Closing for now feel free to reopen if you have further questions.
