### ISSUE TITLE
subdomain always asks for token

### ISSUE THREAD

**Issue by shemgp** [boringproxy/boringproxy#94]
So I run it like: `./boringproxy-linux-x86_64 server -admin-domain subdomain.server.tld`
And accessing `https://subdomain.server.tld` always asks me for the token. Seems it doesn't get logged in.

Thanks for your help.

**Comment by shemgp** [comment]
That was in firefox. In google chrome I get:
![Screenshot from 2021-08-14 23-17-57](https://user-images.githubusercontent.com/1734126/129451041-ebd02557-3f0e-4253-8b08-15e3d7fd8058.png)

**Comment by anderspitman** [comment]
Can you try `/#/tunnels` instead of `/sites#/tunnels`, or maybe `/sites/#/tunnels`?

**Comment by shemgp** [comment]
I don't know what happened but it's working now after I changed the subdomain to `control` it tried get admin certificate again and it worked.
