### ISSUE TITLE
Unable to connect receiving error message from client

### ISSUE THREAD

**Issue by Atiqul-Islam** [boringproxy/boringproxy#95]
Thank you for such a great tool and I really interested in playing with it. However, I am running into a bit of a problem.

I am trying to setup boring proxy for being able to access my raspberry pi camera using mpeg_streamer from the WEB. I have boring proxy server running on an ubuntu server from digital cloud and the boring proxy client running on my raspberry pi. 

The video stream is being served on port 8080 of my raspberry pi.
Attached is an image with the boring proxy tunnel configuration. 

However, when I try to access footage.synchronize.live I get the following error message 

On my client side running on the raspberry pi I get the following error message:

And this is log from the server side running on digital cloud:

Any suggestions will be greatly appreaciated.

**Comment by anderspitman** [comment]
Hey @Atiqul-Islam,

First off, you've posted some pretty sensitive information here, so be careful with that. Someone could use the domain names and token to take control of your boringproxy server. I'd recommend doing a fresh setup once you have it working. And definitely delete that token.

Now for solving your problem. Can you share the command you're using to start the server?

**Comment by anderspitman** [comment]
@Atiqul-Islam closing this. Feel free to reopen if you need to.
